//! Instruction counts for the leader's balance decision (gungraun).
//!
//! One shape, computing the desired assignment for a fleet from an observed
//! store state, parameterized by the state the fleet is in. What changes the
//! decision's cost is which of its three passes has work to do, not which
//! function is called:
//!
//! - `settled_fleet` — every split held by a live member, loads equal. The
//!   sticky pass places everything, the fill pass finds nothing, and the
//!   improving pass runs one full scan to prove there is no move. This is the
//!   tick a healthy fleet pays over and over.
//! - `unowned_pool` — the same pool with nothing owned at all: the tick after
//!   a plan is first published. The fill pass does the whole job
//!   longest-processing-time first, and the improving pass polishes what
//!   greedy left. Read against `settled_fleet`, whose pool size, member count
//!   and lane budgets it shares exactly, so the difference between them is
//!   the fill pass.
//! - `joined_member` — a settled fleet decided over one member more than it
//!   has splits placed on, which is what scaling a deployment up looks like.
//!   The sticky pass keeps every split where it is and the newcomer starts
//!   empty, so nothing but the improving pass can balance it, and that pass
//!   accepts **one move per full `O(members^2 x splits-per-member)` scan**.
//!   This is the only profile whose count is a function of how many moves the
//!   pass accepts rather than of the pool alone, and so **the profile a
//!   change to the improving pass moves**.
//! - `skewed_joined_member` — the same rebalance with one split in twenty a
//!   single multi-gigabyte object, which is what an object at or above the
//!   packing target becomes. Read against `joined_member`, whose pool size,
//!   member count and lane budgets it shares exactly, so the difference is
//!   the weight distribution, which is not a small one. Balance is on
//!   weight, so the newcomer reaches its share here by taking a couple of
//!   multi-gigabyte splits while every incumbent keeps dozens of small ones;
//!   the pass reaches that arrangement through a different, larger number of
//!   scans than the even distribution needs.
//!
//! The two rebalance profiles carry a **smaller pool** than the two static
//! ones, and that is the improving pass's quadratic term rather than a
//! preference: at the larger pool it runs past `10^9` instructions. They are
//! read against each other, never against the pair above them.
//!
//! The three passes are one case rather than three because that is how the
//! leader runs them and because they share state. The fill pass places what
//! the sticky pass left, and the improving pass runs to fixpoint over the
//! result of both. Attribution between them comes from the callgrind profile
//! the run writes either way.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use spate_coordination::bench_seams::{ObservedSplit, Opaque, plan_assignment, snapshot};
use std::collections::{BTreeMap, BTreeSet};
use std::hint::black_box;

#[path = "support/fleet.rs"]
mod fleet;

/// One balance decision: the observed state, the fleet it is decided over,
/// and what the decision must place.
struct Rig {
    splits: Opaque,
    members: BTreeSet<String>,
    reserved: BTreeSet<String>,
    caps: BTreeMap<String, u32>,
    /// How many splits the assignment must name. Asserted rather than
    /// returned unchecked, so a corpus that silently stopped being
    /// assignable could not pass as a fast one.
    expect_assigned: usize,
}

/// A rig over a corpus every one of whose splits is assignable, which every
/// profile here is: the lane budget is well above the per-member share, so
/// the decision places the whole pool or the fixture is wrong.
fn rig(corpus: Vec<ObservedSplit>, fleet: usize) -> Rig {
    let expect_assigned = corpus.len();
    Rig {
        splits: snapshot(corpus),
        members: fleet::members(fleet),
        reserved: BTreeSet::new(),
        caps: fleet::caps(fleet),
        expect_assigned,
    }
}

fn settled_fleet() -> Rig {
    rig(
        fleet::settled(fleet::ASSIGN_SPLITS, fleet::Weights::Packed),
        fleet::MEMBERS,
    )
}

fn unowned_pool() -> Rig {
    rig(
        fleet::fresh(fleet::ASSIGN_SPLITS, fleet::Weights::Packed),
        fleet::MEMBERS,
    )
}

/// The settled fleet with one more member than it has splits placed on. The
/// sticky pass keeps every split where it is and the newcomer starts empty,
/// so only the improving pass can balance it, one split per full scan.
fn joined_member() -> Rig {
    rig(
        fleet::settled(fleet::JOIN_SPLITS, fleet::Weights::Packed),
        fleet::MEMBERS + 1,
    )
}

fn skewed_joined_member() -> Rig {
    rig(
        fleet::settled(fleet::JOIN_SPLITS, fleet::Weights::Skewed),
        fleet::MEMBERS + 1,
    )
}

/// The assignment's total size.
///
/// It lives outside the benchmark function and is `#[inline(never)]`.
/// Collection is bounded by a callgrind toggle on the module the benchmark
/// macro wraps the function in, and a toggle *flips* collection rather than
/// forcing it on, so work the optimizer leaves in an unstable shape inside
/// that module can end up outside the collected region entirely, and a bench
/// that measures nothing still reports a plausible number. The decision
/// itself is a cross-crate call into `bench_seams`, a frame the toggle cannot
/// lose; this loop is the only work written here, so it gets the same
/// treatment.
#[inline(never)]
fn assigned(assignment: &BTreeMap<String, Vec<String>>) -> usize {
    let mut total = 0;
    for splits in assignment.values() {
        total += splits.len();
    }
    total
}

// The corpus is built and snapshotted in the `#[bench]` argument expression,
// which gungraun evaluates outside the collected region, and moved in, so
// the measured work is the leader's, not the fixture builder's. Building the
// observed state is not part of the unit either way: a worker's split map is
// maintained by the store watch and lives across ticks.
//
// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and freeing a
// pool's worth of records there would swamp the decision it is meant to
// measure. A `///` comment is a `#[doc]` attribute, which
// `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::settled_fleet(settled_fleet())]
#[bench::unowned_pool(unowned_pool())]
#[bench::joined_member(joined_member())]
#[bench::skewed_joined_member(skewed_joined_member())]
fn plan(rig: Rig) -> (Rig, BTreeMap<String, Vec<String>>) {
    let assignment = plan_assignment(
        black_box(&rig.splits),
        &rig.members,
        &rig.reserved,
        &rig.caps,
        fleet::LANE_CAP,
        fleet::SEED,
    );
    assert_eq!(
        assigned(&assignment),
        rig.expect_assigned,
        "the decision left splits unassigned with lane budget to spare; if that \
         is intended, the fixture's expectation is the contract being edited"
    );
    (rig, assignment)
}

library_benchmark_group!(name = assignment; benchmarks = plan);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation, and so every `Ir` baseline, is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the decision under measurement rather than to
// whichever frame valgrind's default depth would otherwise cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = assignment
);
