//! Instruction counts for a worker's claim scan (gungraun).
//!
//! One shape — walk an observed store state for the splits this worker may
//! act on and order them — parameterised by the mix of claim kinds the pool
//! holds, because what changes the scan's cost is how far down the
//! eligibility ladder each split falls and how much of the pool survives to
//! be sorted, not which function is called:
//!
//! - `leased_pool` — every split this worker does not hold is under a live
//!   foreign lease. Nothing is claimable, so the walk runs in full, nothing
//!   is materialised and the sort is handed an empty vector. This is the
//!   scan a worker with lane budget to spare pays on every watch event that
//!   reaches it and gets nothing back for — the common case on a fleet whose
//!   peers are all busy. Its cost is the walk and the membership probe
//!   against what this worker already holds, and nothing else.
//! - `unclaimed_pool` — a freshly published plan: nothing owned, nothing
//!   leased, every split a `Create`. The whole pool survives to the sort,
//!   which is handed input already in kind-and-id order — the state is walked
//!   in id order and every candidate shares one kind. So this is the
//!   per-candidate term in isolation: an id clone and a push each, and a sort
//!   over presorted input. Being an allocation per candidate, that term is
//!   dominated by the allocator rather than by anything in this crate, which
//!   is a property of the function and not of the fixture: the count is
//!   linear in the pool, so it tracks a change to what the scan materialises.
//! - `recovering_pool` — a fleet mid-disruption: all four claim kinds
//!   present, terminal and spec-less splits interleaved, and a slice of the
//!   takeovers out of delivery attempts and so parked rather than claimed.
//!   The kinds are drawn independently of the id, so they interleave through
//!   the walk order and the sort has to move most of what it is given.
//!   **This is the profile a change to the claim ordering moves**: read
//!   against `unclaimed_pool`, whose pool size it shares, the difference is
//!   what ordering a genuinely unordered input costs.
//!
//! The eligibility walk, the attempts gate and the sort are one case rather
//! than three because the scan exists to produce an *ordered* list — a
//! candidate list nobody ordered is not a thing the worker ever holds.
//! Attribution between them comes from the callgrind profile the run writes
//! either way.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use spate_coordination::bench_seams::{ClaimCensus, ObservedSplit, Opaque, scan_claims, snapshot};
use std::collections::BTreeSet;
use std::hint::black_box;

#[path = "support/fleet.rs"]
mod fleet;

/// One claim scan: the observed state, what this worker already holds, and
/// how the scan must classify the pool.
struct Rig {
    splits: Opaque,
    owned: BTreeSet<String>,
    /// `[create, released, reclaim, expired, quarantined]`. Asserted rather
    /// than returned unchecked, so a corpus that silently stopped carrying a
    /// claim kind could not pass as a fast one — the mix *is* what
    /// distinguishes these profiles from each other.
    expect_census: ClaimCensus,
}

fn rig(corpus: Vec<ObservedSplit>, owned: BTreeSet<String>, expect_census: ClaimCensus) -> Rig {
    Rig {
        splits: snapshot(corpus),
        owned,
        expect_census,
    }
}

/// Nothing owned: the tick after a plan is first published, before this
/// worker has claimed anything. Every split is a `Create`.
fn unclaimed_pool() -> Rig {
    let corpus = fleet::fresh(fleet::SCAN_SPLITS, fleet::Weights::Packed);
    rig(corpus, BTreeSet::new(), [fleet::SCAN_SPLITS, 0, 0, 0, 0])
}

/// Every peer busy: this worker holds its lane budget's worth and everything
/// else is under a live foreign lease, so no split is claimable.
fn leased_pool() -> Rig {
    let corpus = fleet::leased(fleet::SCAN_SPLITS);
    let owned = fleet::owned(&corpus);
    rig(corpus, owned, [0, 0, 0, 0, 0])
}

/// A fleet recovering: every claim kind present, and the attempts gate
/// reached by a slice of the takeovers.
fn recovering_pool() -> Rig {
    let corpus = fleet::recovering(fleet::SCAN_SPLITS);
    let owned = fleet::owned(&corpus);
    rig(corpus, owned, fleet::RECOVERING_CENSUS)
}

// The corpus is built and snapshotted in the `#[bench]` argument expression,
// which gungraun evaluates outside the collected region, and moved in — so
// the measured work is the worker's, not the fixture builder's. Building the
// observed state is not part of the unit either way: the split map is
// maintained by the store watch and lives across ticks.
//
// Each case returns its rig, and the candidates come back inside an opaque
// box rather than being dropped: a value dropped inside the collected region
// charges the count for teardown, and a scan's worth of split ids is not a
// small teardown. A `///` comment is a `#[doc]` attribute, which
// `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::leased_pool(leased_pool())]
#[bench::unclaimed_pool(unclaimed_pool())]
#[bench::recovering_pool(recovering_pool())]
fn scan(rig: Rig) -> (Rig, Opaque) {
    let (candidates, census) = scan_claims(
        black_box(&rig.splits),
        &rig.owned,
        fleet::INSTANCE,
        fleet::MAX_ATTEMPTS,
    );
    assert_eq!(
        census, rig.expect_census,
        "the scan classified the pool differently; if that is intended, the \
         fixture's expectation is the contract being edited"
    );
    (rig, candidates)
}

library_benchmark_group!(name = claims; benchmarks = scan);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the scan under measurement rather than to
// whichever frame valgrind's default depth would otherwise cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = claims
);
