//! Instruction counts for the watermark controller and the in-flight budget
//! (gungraun).
//!
//! One shape — 32,768 poll iterations, each a movement of the
//! [`InflightBudget`](spate_core::backpressure::InflightBudget) plus one
//! [`WatermarkController::tick`](spate_core::backpressure::WatermarkController::tick)
//! over it — parameterized by the pressure the pipeline is under, because
//! what changes the cost is which arm of the state machine runs, not which
//! function is called.
//!
//! This is the most frequently executed synchronous code the framework has:
//! `tick` runs once per poll iteration on every pipeline thread, whether or
//! not anything is happening, and the budget is touched on every seal and
//! every acknowledgment. It is also the code an instruction count describes
//! better than a wall clock — one iteration is tens of instructions, well
//! under the resolution of the timer that would have to measure it, and the
//! path is atomics and branches with no allocation anywhere in it.
//!
//! - `quiet_traffic` — in-flight bytes ride at a fraction of the low
//!   watermark, climbing a chunk at a time as fifteen seals land and dropping
//!   back in one as their acknowledgments return; queues stay drained,
//!   nothing bounces. Every iteration moves the reading, so this is not a
//!   `tick` over a static budget — and both of the budget's saturating
//!   read-modify-writes run on every one of them whichever way it moved,
//!   since the script hands `add` and `sub` the movement and a zero rather
//!   than calling one of them. `tick` then takes the `Normal` arm, reads the
//!   budget, finds it under the high watermark and returns nothing. This is
//!   the iteration a healthy pipeline pays for hours at a time, and the floor
//!   the other two are read against.
//! - `congested_traffic` — usage climbs past the high watermark and stays
//!   there, the driver never reports its queues drained, and a `try_send`
//!   bounces every sixty-fourth iteration. One transition at the top, then
//!   every later `tick` takes the `Paused` arm and declines to resume by one
//!   of two routes. On the iterations a rejection landed it returns at the
//!   rejection check, before the drained test — the clock read that restarts
//!   the pause floor happened in `on_send_rejected`, not here. On every other
//!   iteration it reaches the drained test, whose first conjunct is already
//!   false because usage is above the high watermark, so `queues_below_low`
//!   is never read and the clock is never consulted at all. The profile is
//!   therefore the *cheap* half of the `Paused` arm, which is what makes
//!   `flapping_traffic` the one that prices the rest of it.
//! - `flapping_traffic` — the adversary. Usage slams from above the high
//!   watermark to below the low one and back on a sixteen-iteration phase,
//!   which is longer than the minimum-pause floor, so nothing but the
//!   watermarks decides the outcome and the controller transitions as often
//!   as its hysteresis permits. **This is the profile a change to the
//!   hysteresis moves**: read against `quiet_traffic`, whose iteration count
//!   and script length it shares exactly, the difference is what taking a
//!   transition costs over declining one.
//!
//! Deliberately absent is a sweep of the watermark ratios or the pause floor.
//! Both are comparisons against a field — `usage() >= high_bytes`,
//! `duration_since(since) >= min_pause` — so their *values* cannot change the
//! instruction count, only which arm the comparison selects, and the three
//! profiles already put every arm under measurement. Three cases, not a
//! matrix: callgrind runs the workload under emulation.
//!
//! The controller reads time through its injected
//! [`Clock`](spate_core::backpressure::Clock) rather than the monotonic
//! default. That seam exists so hysteresis can be driven without sleeping,
//! and taking it here is what keeps the case measuring this crate: a real
//! `Instant::now` costs more per call than the state machine around it, and a
//! count dominated by a libc time read would move with the C library rather
//! than with the code the case names. Virtual time advances explicitly, once
//! per iteration, inside the measured loop.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use std::hint::black_box;

#[path = "support/poll_traffic.rs"]
mod poll_traffic;

use poll_traffic::{Profile, Rig, rig};

/// Transitions each script produces, pinned here rather than recomputed by
/// the rig: a rig that derived the expectation from its own model of the
/// state machine would agree with itself however the machine changed. A quiet
/// pipeline never transitions; a congested one pauses once and never finds a
/// reason to resume; the adversary takes a pause and a resume in every
/// thirty-two-iteration cycle.
const QUIET_TRANSITIONS: usize = 0;
const CONGESTED_TRANSITIONS: usize = 1;
const FLAPPING_TRANSITIONS: usize = 2048;

/// The whole script, one poll iteration at a time.
///
/// It lives outside the benchmark function and is `#[inline(never)]`, and
/// both halves of that are load-bearing rather than stylistic. Collection is
/// bounded by a callgrind toggle on the module the benchmark macro wraps the
/// function in, and a toggle *flips* collection rather than forcing it on —
/// so work the optimizer leaves in an unstable shape inside that module can
/// end up outside the collected region entirely, and a bench that measures
/// nothing still reports a plausible number. This loop is the most exposed
/// of any in the suite: every call it makes is a small, inlinable,
/// same-crate-graph function with no erasure boundary anywhere in it, so the
/// named frame is the only thing anchoring the region.
#[inline(never)]
fn drive(rig: &mut Rig) -> usize {
    rig.drive()
}

// The script is built in the `#[bench]` argument expression, which gungraun
// evaluates outside the collected region — so the measured work is the
// controller's, not the script builder's. There is no warm-up drive: the
// controller carries state across iterations by design, and a second drive
// would start it mid-hysteresis rather than in the state a pipeline thread
// creates it in.
//
// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and freeing a
// 32,768-entry script there would swamp the loop it is meant to measure. A
// `///` comment here is a `#[doc]` attribute, which `#[library_benchmark]`
// rejects.
#[library_benchmark]
#[bench::quiet_traffic(rig(Profile::Quiet, QUIET_TRANSITIONS))]
#[bench::congested_traffic(rig(Profile::Congested, CONGESTED_TRANSITIONS))]
#[bench::flapping_traffic(rig(Profile::Flapping, FLAPPING_TRANSITIONS))]
fn poll_iterations(mut rig: Rig) -> Rig {
    let transitions = black_box(drive(&mut rig));
    assert_eq!(
        transitions, rig.expect_transitions,
        "the script produced a different number of transitions than its \
         profile claims, so it is no longer exercising the arm the case names; \
         if that is intended, the fixture's expectation is the contract being \
         edited"
    );
    rig
}

library_benchmark_group!(name = backpressure; benchmarks = poll_iterations);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute a heap block to the code under measurement rather
// than to whichever frame the default depth of 4 happens to cut at — which
// here should attribute nothing at all, since the measured path allocates
// nowhere.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = backpressure
);
