//! Instruction counts for the operator-chain hot path (gungraun).
//!
//! The same two rigs `benches/chain.rs` times, counted instead of timed:
//! callgrind's instruction count is deterministic, so it compares across the
//! shared CI runners where a wall-clock number is only noise. DHAT runs
//! alongside callgrind in the same invocation, so both cases also report
//! deterministic heap counts. `tests/chain_alloc.rs` bounds the chain's
//! allocation *count* absolutely; DHAT adds bytes and the t-gmax peak, which
//! a buffer that doubles in place moves without a new allocation. Two cases,
//! not the full divan matrix — callgrind runs the workload under emulation.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use std::hint::black_box;

#[path = "support/chain_rig.rs"]
mod chain_rig;

use chain_rig::{Rig, borrowed_rig, owned_rig};

/// Build the rig and drive one batch through it, so the measured batch sees
/// warm shard queues and chunk buffers. Everything a `#[bench]` argument
/// expression does is evaluated outside the collected region.
fn warmed(mut rig: Rig) -> Rig {
    rig.drive();
    rig
}

// One batch of 512 payloads through the chain.
//
// Returns the rig rather than dropping it: a value moved into the benchmark
// function is dropped inside the collected region, which would charge the
// count for tearing down the chain and its queues. A `///` comment here is a
// `#[doc]` attribute, which `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::borrowed(warmed(borrowed_rig()))]
#[bench::owned(warmed(owned_rig()))]
fn push_batch(mut rig: Rig) -> Rig {
    black_box(rig.drive());
    rig
}

library_benchmark_group!(name = chain; benchmarks = push_batch);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough that heap blocks attribute to the chain under measurement
// rather than to whichever frame the default depth of 4 happens to cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = chain
);
