//! Instruction counts for the multi-sink split terminal (gungraun).
//!
//! One shape — one poll batch of 8,192 payloads deserialized straight into a
//! [`split`](spate_core::ops::ChainBuilder::split) terminal and dispatched to
//! typed branches, drained to encoded chunks — parameterized by the two
//! things a split varies that a single-sink chain cannot express at all.
//! `benches/chain_gungraun.rs` measures the framework's *other* terminal, one
//! table with one encoder; this one measures the terminal that fans a
//! heterogeneously-typed stream across many, where every record pays a
//! per-emit `Any` downcast to recover its branch's concrete type and then a
//! virtual call each through that branch's boxed router and encoder.
//!
//! - **The branch count.** Every branch is a `SinkHandoff` of its own, with
//!   its own encoder clone, chunk buffer and `AckSet`, and the terminal's
//!   `flush` and `relieve` walk all of them. `two_branches` and
//!   `four_branches` carry the same 8,192 payloads and the same per-payload
//!   bytes, spread two and four ways, so the pair is what declaring a
//!   destination costs when the record count does not change.
//! - **The match-hit ratio.** `four_branches_quarter_unrouted` is
//!   `four_branches` with every fourth payload carrying a tag no arm of the
//!   route closure names. Those records reach no branch, so the terminal
//!   takes its `unmatched` arm instead of a dispatch: read against
//!   `four_branches`, whose corpus size, payload width and branch count it
//!   shares exactly, the difference is what a dispatch costs over a
//!   drop-and-count.
//!
//! The `unmatched` policy is [`Skip`](spate_core::error::ErrorPolicy::Skip)
//! rather than `Fail` because `Fail` latches a fatal on the first unrouted
//! record and short-circuits the rest of the batch — a case built that way
//! would measure the short-circuit, not the policy.
//!
//! Deliberately absent is the unrouted ratio at two branches, and any sweep
//! of shards or chunk target inside a branch. The `unmatched` arm is reached
//! on `emitted == 0` and never touches a branch, so it cannot be a function
//! of how many branches exist; and a branch *is* a `SinkHandoff`, whose shard
//! and chunk axes `benches/chain_gungraun.rs` already sweeps against the same
//! code. Three cases, not twelve: callgrind runs the workload under
//! emulation.
//!
//! DHAT runs alongside callgrind in the same invocation, so every case also
//! reports deterministic heap counts — which for a split is worth its own
//! look, since each branch reserves and hands off a chunk buffer of its own.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use std::hint::black_box;

#[path = "support/split_rig.rs"]
mod split_rig;

use split_rig::{Rig, Tags, four_branch_rig, two_branch_rig};

/// Build the rig and drive one batch through it, so the measured batch sees
/// warm shard queues and chunk buffers. Everything a `#[bench]` argument
/// expression does is evaluated outside the collected region.
fn warmed(mut rig: Rig) -> Rig {
    rig.drive();
    rig
}

/// One batch through the split terminal.
///
/// It lives outside the benchmark function and is `#[inline(never)]`, and
/// both halves of that are load-bearing rather than stylistic. Collection is
/// bounded by a callgrind toggle on the module the benchmark macro wraps the
/// function in, and a toggle *flips* collection rather than forcing it on —
/// so work the optimizer leaves in an unstable shape inside that module can
/// end up outside the collected region entirely, and a bench that measures
/// nothing still reports a plausible number. The batch reaches the chain
/// through the boxed `RunnableChain` seam, which is a frame the toggle cannot
/// lose; this call is given the same treatment so the drain sweep around it
/// is inside a frame of its own too.
#[inline(never)]
fn drive(rig: &mut Rig) -> usize {
    rig.drive()
}

// The corpus is built and the chain assembled in the `#[bench]` argument
// expression, which gungraun evaluates outside the collected region — so the
// measured work is the terminal's, not the fixture builder's.
//
// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, which would
// charge the count for tearing down four chains' worth of queues. A `///`
// comment here is a `#[doc]` attribute, which `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::two_branches(warmed(two_branch_rig()))]
#[bench::four_branches(warmed(four_branch_rig(Tags::FourBranches)))]
#[bench::four_branches_quarter_unrouted(warmed(four_branch_rig(
    Tags::FourBranchesQuarterUnrouted
)))]
fn dispatch_batch(mut rig: Rig) -> Rig {
    let rows = black_box(drive(&mut rig));
    assert_eq!(
        rows, rig.expect_rows,
        "the batch reached a different number of branch rows than the corpus \
         routes; if that is intended, the fixture's expectation is the \
         contract being edited"
    );
    rig
}

library_benchmark_group!(name = split; benchmarks = dispatch_batch);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough that heap blocks attribute to the terminal under measurement
// rather than to whichever frame the default depth of 4 happens to cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = split
);
