//! Instruction counts for the worker's descriptor decode (gungraun).
//!
//! The leader's half of the split descriptor is already counted: `plan`
//! encodes one per split inside its measured region. This is the other half,
//! and it is not the same number read backwards. A worker decodes a
//! descriptor when it opens a split, and again when it validates a resume,
//! which the driver only does for a split gained with carried progress, so a
//! resumed split pays it twice and a fresh one once. The parse allocates a
//! `String` for every key and every ETag where the serializer only borrowed
//! them, and
//! `decode` runs the parser **twice over the same bytes**, probing the
//! version before parsing the document, so an incompatible descriptor is
//! reported as a version mismatch rather than as a parse error.
//!
//! One shape, decoding a plan's worth of descriptors as the worker-side
//! mirror of planning a listing's worth of splits, parameterized by how the
//! same member count is arranged. What a change to this path moves is the
//! split between per-document and per-member work:
//!
//! - `full_splits` — 400 descriptors of 16 members, which is what the
//!   open-cost floor produces from an ordinary listing. Per-member field
//!   parsing dominates, and this is the denominator the other case is read
//!   against.
//! - `single_member_splits` — the same 6,400 members as one member each, the
//!   shape a listing of at-or-above-target objects produces. Sixteen times
//!   the documents for the same members, so the difference between the two is
//!   the per-document term: the version probe, the document wrapper, and the
//!   `SplitDescriptor` allocation. **This is the profile a byte-range
//!   subdivision change moves in the opposite direction to `plan`'s
//!   `big_objects`**: subdividing turns one such descriptor into several
//!   members, trading documents for members.
//!
//! Descriptors are encoded in the fixture, never in the measured region, so
//! these count parsing only.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use spate_s3::SplitDescriptor;
use std::hint::black_box;

#[path = "support/descriptors.rs"]
mod descriptors;

// The corpus is encoded in the `#[bench]` argument expression, which gungraun
// evaluates outside the collected region, and moved in. Both the encoded
// bytes and the decoded descriptors are handed back rather than dropped in
// place: freeing several thousand documents and the strings parsed out of
// them inside the region would charge the count for teardown. A `///`
// comment is a `#[doc]` attribute, which `#[library_benchmark]` rejects.
//
/// The measured work: a plan's worth of descriptors parsed in one pass.
///
/// It lives outside the benchmark function and is `#[inline(never)]`.
/// Collection is bounded by a callgrind toggle on the module the benchmark
/// macro wraps the function in, and a toggle *flips* collection rather than
/// forcing it on, so work the optimizer leaves in an unstable shape inside
/// that module can end up outside the collected region entirely. Two earlier
/// revisions of this bench showed it: one built the vector with
/// `.iter().map().collect()` and counted 3,249 Ir, the other used a plain
/// `for` in the benchmark function and counted 858,925 Ir whose callgrind
/// profile was **100% glibc `malloc_consolidate` and `unlink_chunk`**, with
/// no `serde_json` frame at all and the same total whether the corpus held
/// 400 documents or 6,400.
///
/// A named, never-inlined callee is a frame the toggle cannot lose, which the
/// two working benches in this crate get by calling into `bench_seams`. This
/// one reaches its work through public API instead, so the callee lives here.
#[inline(never)]
fn decode_plan(encoded: &[Vec<u8>]) -> Vec<SplitDescriptor> {
    let mut decoded = Vec::with_capacity(encoded.len());
    for bytes in encoded {
        decoded.push(SplitDescriptor::decode(bytes).expect("the fixture decodes"));
    }
    decoded
}

#[library_benchmark]
#[bench::full_splits(descriptors::full_split_plan())]
#[bench::single_member_splits(descriptors::single_member_plan())]
fn decode(encoded: Vec<Vec<u8>>) -> (Vec<Vec<u8>>, Vec<SplitDescriptor>) {
    let decoded = decode_plan(black_box(&encoded));
    // Asserted rather than returned unchecked, so a fixture that silently
    // stopped carrying members could not pass as a fast one. Walked with a
    // `for` rather than an iterator chain: a closure here is exactly the
    // shape that went missing from the collected region above.
    let mut members = 0;
    for descriptor in &decoded {
        assert!(
            descriptor.objects.len() <= descriptors::MEMBERS_PER_SPLIT,
            "a descriptor carries more members than the open-cost floor permits"
        );
        members += descriptor.objects.len();
    }
    assert_eq!(
        members,
        descriptors::MEMBERS,
        "the corpus decoded to a different member count"
    );
    (encoded, decoded)
}

library_benchmark_group!(name = descriptor; benchmarks = decode);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation, and so every `Ir` baseline, is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the parse under measurement rather than to
// whichever frame valgrind's default depth would otherwise cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = descriptor
);
