//! Instruction counts for chunk-fed record framing (gungraun).
//!
//! One shape — drive a run of objects through one framer, as a lane does over
//! the members of its split — parameterized by codec and by how the object is
//! entered:
//!
//! - `plain_whole` — one 4 MiB NDJSON object in fetch-sized chunks. The
//!   per-byte cost of the whole lane, and the denominator here.
//! - `gzip_whole`, `zstd_whole` — the same body stored compressed. These are
//!   the **negative control** for byte-range subdivision: a whole-stream
//!   codec cannot be entered at an arbitrary offset, so subdivision must
//!   never apply to them. If either count moves when subdivision lands, the
//!   capability probe has leaked into the whole-stream path.
//! - `gzip_multi_member`, `zstd_multi_frame` — the same body again, stored as
//!   sixteen independently-encoded streams concatenated into one object,
//!   which is what an export key appended to by a run of upload sessions
//!   holds. Decoded content is byte-identical to the `_whole` pair, so the
//!   difference between them is the per-stream term those fixtures never
//!   charge — trailer validation, decoder reinitialization, the next stream's
//!   header parse — **plus** whatever the compressed input's own shape
//!   contributes, since sixteen streams each starting from a cleared window
//!   do not compress to the same bytes as one. The pair bounds that term
//!   rather than isolating it. Both codecs have to read every stream; a
//!   decoder that stopped at the first would drop fifteen sixteenths of the
//!   object, and the asserted record count turns that into a failure rather
//!   than into a welcome fall in the number.
//! - `plain_mid_offset` — the same object fed from a byte offset that falls
//!   *inside* a record, which is what a reader entering a subdivided object
//!   faces. The case asserts the record count, and that assertion is the
//!   point: today the framer emits the partial leading line as a record, so
//!   a subdivision change has to come here and say what the new contract is
//!   rather than drift past it.
//! - `plain_many_small` — sixteen small objects through one framer. The
//!   open-cost floor caps a split at ~16 members, so this is a full split's
//!   worth of per-object codec resolution and state reset — the cost that
//!   grows when subdivision turns one object into several.
//!
//! Bodies are compressed in the fixture, never in the measured region, so
//! these count decompression only. Framing is done with `spate-json`'s
//! `NdjsonFramer` rather than a local copy: this crate ships no framer of its
//! own, and object storage carrying newline-delimited JSON is the pairing
//! production actually runs.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use spate_json::NdjsonFramer;
use spate_s3::Compression;
use spate_s3::bench_seams::{MakeFramer, frame_objects};
use std::hint::black_box;
use std::sync::Arc;

#[path = "support/ndjson.rs"]
mod ndjson;

/// One framing job: the codec the objects are stored under, and the objects
/// themselves as `(key, chunks)`.
struct Rig {
    compression: Compression,
    objects: Vec<(String, Vec<Vec<u8>>)>,
    /// What the framer must emit. Asserted rather than returned so a fixture
    /// that silently stops producing records cannot pass as a fast one.
    expect_records: usize,
}

fn make_framer() -> MakeFramer {
    Arc::new(|| Box::new(NdjsonFramer::new(ndjson::MAX_RECORD_BYTES)))
}

/// One object whose body is transformed by `store` — identity for plain, a
/// compressor otherwise — under a key whose extension matches.
///
/// Every case runs `Compression::Auto`, which is the shipped default and the
/// only setting that consults the key at all: under an explicit `Gzip` or
/// `Zstd` the resolver returns immediately and the extension is dead weight.
/// Passing `Auto` is what makes the per-object codec resolution these cases
/// claim to measure the same work production does.
fn one_object(compression: Compression, suffix: &str, store: impl Fn(&[u8]) -> Vec<u8>) -> Rig {
    let body = ndjson::whole_body();
    let expect_records = body.iter().filter(|&&b| b == b'\n').count();
    let stored = store(&body);
    Rig {
        compression,
        objects: vec![(
            format!("part-000000.ndjson{suffix}"),
            ndjson::chunks(&stored),
        )],
        expect_records,
    }
}

fn plain_whole() -> Rig {
    one_object(Compression::Auto, "", <[u8]>::to_vec)
}

fn gzip_whole() -> Rig {
    one_object(Compression::Auto, ".gz", ndjson::gzip)
}

fn zstd_whole() -> Rig {
    one_object(Compression::Auto, ".zst", ndjson::zstd)
}

/// One object whose body is stored as several independent streams.
///
/// The decoded bytes are the whole body either way, so `expect_records` is
/// the same count the `_whole` case asserts — which is the assertion that
/// matters here: a decoder that stopped at the first stream would return one
/// sixteenth of the records and fail rather than report a smaller number.
fn multi_part_object(suffix: &str, store: impl Fn(&[u8]) -> Vec<u8>) -> Rig {
    let stored = ndjson::concatenated(store);
    Rig {
        compression: Compression::Auto,
        objects: vec![(
            format!("part-000000.ndjson{suffix}"),
            ndjson::chunks(&stored),
        )],
        expect_records: ndjson::RECORDS,
    }
}

fn gzip_multi_member() -> Rig {
    multi_part_object(".gz", ndjson::gzip)
}

fn zstd_multi_frame() -> Rig {
    multi_part_object(".zst", ndjson::zstd)
}

/// The same object entered part-way through a record.
///
/// The expected count is derived from the fixture rather than written down,
/// so it tracks the record shape — but the *rule* it encodes is the thing
/// under review: the leading partial line counts as a record today, because
/// the framer has no way to know it entered mid-record. A reader that
/// discarded through the first delimiter would emit one fewer, and this is
/// where that change has to be stated.
fn plain_mid_offset() -> Rig {
    let body = ndjson::whole_body();
    let at = ndjson::offset_inside_a_record(&body, body.len() / 2);
    let tail = &body[at..];
    let expect_records =
        tail.iter().filter(|&&b| b == b'\n').count() + usize::from(!tail.ends_with(b"\n"));
    Rig {
        compression: Compression::Auto,
        objects: vec![("part-000000.ndjson".to_owned(), ndjson::chunks(tail))],
        expect_records,
    }
}

/// A full split's worth of members through one framer.
fn plain_many_small() -> Rig {
    let (objects_n, records_each) = (ndjson::RUN_OBJECTS, ndjson::RUN_RECORDS_EACH);
    let objects = (0..objects_n)
        .map(|i| {
            let body = ndjson::body(i * records_each, records_each);
            (format!("part-{i:06}.ndjson"), ndjson::chunks(&body))
        })
        .collect();
    Rig {
        compression: Compression::Auto,
        objects,
        expect_records: objects_n * records_each,
    }
}

// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and freeing a
// few megabytes of chunk buffers would swamp the framing it is meant to
// measure. A `///` comment is a `#[doc]` attribute, which
// `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::plain_whole(plain_whole())]
#[bench::gzip_whole(gzip_whole())]
#[bench::zstd_whole(zstd_whole())]
#[bench::gzip_multi_member(gzip_multi_member())]
#[bench::zstd_multi_frame(zstd_multi_frame())]
#[bench::plain_mid_offset(plain_mid_offset())]
#[bench::plain_many_small(plain_many_small())]
fn frame(rig: Rig) -> Rig {
    let records = frame_objects(rig.compression, make_framer(), black_box(&rig.objects))
        .expect("the fixture frames cleanly");
    assert_eq!(
        records, rig.expect_records,
        "framed record count changed; if that is intended, the fixture's \
         expectation is the contract being edited"
    );
    rig
}

library_benchmark_group!(name = framing; benchmarks = frame);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the framing under measurement rather than to
// whichever frame the default depth of 4 happens to cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = framing
);
