//! Instruction counts for the leader's planning work (gungraun).
//!
//! One shape — pack a listing into splits and mint each split's id —
//! parameterised by the listing profile, because what changes packing's cost
//! is where the objects sit relative to the split target and the open-cost
//! floor, not which function is called:
//!
//! - `uniform_small` — 10,000 objects well under the target. The ordinary
//!   backfill listing, and the denominator the other two are read against.
//! - `big_objects` — 2,000 objects at or above the target, each closing a
//!   bin on its own. **This is the profile a byte-range subdivision change
//!   moves**: subdividing turns one such object into `ceil(size / target)`
//!   members, which changes both the input cardinality and the digest count.
//! - `mixed_tail` — tiny-object runs interleaved with large ones, holding
//!   the open-bin deque at `PACKING_LOOKBACK` so its linear scan runs at
//!   worst case on every placement.
//!
//! Packing and minting are one case rather than two on purpose: minting is
//! per-split work the planner always does immediately after packing, and
//! folding them together makes a preimage built with `format!` per member
//! visible without a case of its own. Attribution between the two comes from
//! the callgrind profile, which the run writes either way.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use spate_s3::bench_seams::plan_listing;
use std::hint::black_box;

#[path = "support/listing.rs"]
mod listing;

// The corpus is built in the `#[bench]` argument expression, which gungraun
// evaluates outside the collected region, and moved in — so the measured work
// is the planner's, not the fixture builder's. The returned ids are handed
// back rather than dropped in place: dropping a few thousand `SplitId`s
// inside the region would charge the count for teardown.
#[library_benchmark]
#[bench::uniform_small(listing::uniform_small())]
#[bench::big_objects(listing::big_objects())]
#[bench::mixed_tail(listing::mixed_tail())]
fn plan(objects: Vec<(String, u64, String)>) -> Vec<spate_core::coordination::SplitId> {
    let ids = plan_listing(black_box(objects), listing::TARGET_BYTES);
    assert!(!ids.is_empty(), "a non-empty listing planned no splits");
    ids
}

library_benchmark_group!(name = split; benchmarks = plan);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the packing under measurement rather than to
// whichever frame the default depth of 4 happens to cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = split
);
