//! Instruction counts for the row encoders (gungraun).
//!
//! One shape — encode a block of rows and finish the chunk, exactly as the
//! sink's terminal stage does — parameterised by wire format and row schema.
//!
//! The two formats are the choice a deployment actually makes.
//! [`Native`](spate_clickhouse::NativeEncoder) buffers column-wise and emits a
//! block; RowBinary serialises each row in place. Their relative cost is
//! published on the ClickHouse format page from a wall-clock measurement, and
//! nothing counted stood behind that until now.
//!
//! The two schemas exercise different halves of the encoder. `events` is wide
//! and string-heavy — LowCardinality dictionaries, a Nullable null-map, an
//! Array with its offsets, a Decimal — while `metrics` is narrow and almost
//! entirely fixed-width. A change that speeds up dictionary handling and slows
//! down fixed-width columns moves the two in opposite directions, which either
//! schema alone would hide.
//!
//! The measured region is a whole chunk, not one row. A ClickHouse insert is a
//! block: per-row work is only meaningful amortised over one, and the Native
//! encoder's `finish_chunk` — which reserves once and lays out every column —
//! is where a large part of its cost lives.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use bytes::BytesMut;
use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use serde::Serialize;
use spate_clickhouse::{ClickHouseEncoder, NativeEncoder, NativeSchema};
use spate_core::checkpoint::AckRef;
use spate_core::deser::Owned;
use spate_core::record::{PartitionId, Record, RecordMeta};
use spate_core::sink::RowEncoder;
use std::hint::black_box;

#[path = "support/rows.rs"]
mod rows;

use rows::{EventRow, MetricRow, ROWS};

/// A record carrying one row. The ack receiver is leaked rather than held:
/// the rig never resolves a batch, and dropping the receiver inside the
/// measured region would charge the count for teardown that the sink does not
/// do per row.
fn record<T>(payload: T) -> Record<T> {
    let (ack, rx) = AckRef::test_pair();
    std::mem::forget(rx);
    Record {
        payload,
        meta: RecordMeta {
            partition: PartitionId(0),
            offset: 0,
            event_time_ms: 0,
            key_hash: None,
        },
        ack,
    }
}

/// One encoder with the rows it encodes and a buffer sized to hold the result,
/// so the measurement is the encoder's work rather than the allocator growing
/// a `BytesMut` under it.
struct Rig<E, T> {
    enc: E,
    records: Vec<Record<T>>,
    buf: BytesMut,
}

/// The measured work: a whole chunk through one encoder.
fn encode_chunk<E, T>(rig: &mut Rig<E, T>)
where
    E: RowEncoder<Owned<T>>,
    T: Send + 'static,
{
    rig.buf.clear();
    for rec in &rig.records {
        rig.enc.encode(black_box(rec), &mut rig.buf).unwrap();
    }
    rig.enc.finish_chunk(&mut rig.buf).unwrap();
    assert!(!rig.buf.is_empty(), "encoder produced no bytes");
}

fn native_rig<T: Serialize + Send + 'static>(
    cols: &[(&str, &str)],
    payloads: Vec<T>,
) -> Rig<NativeEncoder<Owned<T>>, T> {
    let schema = NativeSchema::from_columns(cols).expect("native schema builds");
    Rig {
        enc: NativeEncoder::<Owned<T>>::new(schema),
        records: payloads.into_iter().map(record).collect(),
        buf: BytesMut::with_capacity(1 << 20),
    }
}

fn rowbinary_rig<T: Serialize + Send + 'static>(
    payloads: Vec<T>,
) -> Rig<ClickHouseEncoder<Owned<T>>, T> {
    Rig {
        enc: ClickHouseEncoder::<Owned<T>>::new(),
        records: payloads.into_iter().map(record).collect(),
        buf: BytesMut::with_capacity(1 << 20),
    }
}

fn native_events() -> Rig<NativeEncoder<Owned<EventRow>>, EventRow> {
    native_rig(&rows::event_columns(), rows::events(ROWS))
}

fn native_metrics() -> Rig<NativeEncoder<Owned<MetricRow>>, MetricRow> {
    native_rig(&rows::metric_columns(), rows::metrics(ROWS))
}

fn rowbinary_events() -> Rig<ClickHouseEncoder<Owned<EventRow>>, EventRow> {
    rowbinary_rig(rows::events(ROWS))
}

fn rowbinary_metrics() -> Rig<ClickHouseEncoder<Owned<MetricRow>>, MetricRow> {
    rowbinary_rig(rows::metrics(ROWS))
}

// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and freeing a
// thousand rows of owned strings would swamp the encode it is meant to
// measure. A `///` comment is a `#[doc]` attribute, which
// `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::native_events(native_events())]
fn encode_native_events(
    mut rig: Rig<NativeEncoder<Owned<EventRow>>, EventRow>,
) -> Rig<NativeEncoder<Owned<EventRow>>, EventRow> {
    encode_chunk(&mut rig);
    rig
}

#[library_benchmark]
#[bench::native_metrics(native_metrics())]
fn encode_native_metrics(
    mut rig: Rig<NativeEncoder<Owned<MetricRow>>, MetricRow>,
) -> Rig<NativeEncoder<Owned<MetricRow>>, MetricRow> {
    encode_chunk(&mut rig);
    rig
}

#[library_benchmark]
#[bench::rowbinary_events(rowbinary_events())]
fn encode_rowbinary_events(
    mut rig: Rig<ClickHouseEncoder<Owned<EventRow>>, EventRow>,
) -> Rig<ClickHouseEncoder<Owned<EventRow>>, EventRow> {
    encode_chunk(&mut rig);
    rig
}

#[library_benchmark]
#[bench::rowbinary_metrics(rowbinary_metrics())]
fn encode_rowbinary_metrics(
    mut rig: Rig<ClickHouseEncoder<Owned<MetricRow>>, MetricRow>,
) -> Rig<ClickHouseEncoder<Owned<MetricRow>>, MetricRow> {
    encode_chunk(&mut rig);
    rig
}

library_benchmark_group!(
    name = encode;
    benchmarks =
        encode_native_events,
        encode_native_metrics,
        encode_rowbinary_events,
        encode_rowbinary_metrics
);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the encode under measurement rather than to
// whichever frame the default depth of 4 happens to cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = encode
);
