//! Instruction counts for the row encoders (gungraun).
//!
//! One shape, encoding a block of rows and finishing the chunk as the sink's
//! terminal stage does, parameterized by wire format and row schema.
//!
//! The two formats are the choice a deployment makes.
//! [`Native`](spate_clickhouse::NativeEncoder) buffers column-wise and emits a
//! block; RowBinary serializes each row in place. Their relative cost is
//! published on the ClickHouse format page from a wall-clock measurement; this
//! is the counted number underneath it.
//!
//! The schemas exercise different halves of the encoder. `events` is wide
//! and string-heavy (LowCardinality dictionaries, a Nullable null-map, an
//! Array with its offsets, a Decimal) while `metrics` is narrow and almost
//! entirely fixed-width. A change that speeds up dictionary handling and slows
//! down fixed-width columns moves the two in opposite directions, which either
//! schema alone would hide.
//!
//! `exotic` is the third, and Native-only. It holds the column types neither
//! of the others reaches: `Map`, `Tuple`, `FixedString`, the fixed-width
//! blobs (`UUID`, `IPv6`, `Int256`, `UInt256`), `Enum8`/`Enum16` and
//! `LowCardinality(Nullable(String))`, each of which has its own
//! [`ColumnWriter`](spate_clickhouse::native) arm, several of them bypassing
//! the column serializer for a raw byte sink.
//!
//! Native-only is a limit, not an absence. RowBinary here is this crate's own
//! serializer, not the `clickhouse` crate's, and `exotic` does reach arms of
//! it that no other corpus does: `serialize_map`, `serialize_tuple` (both
//! tuples and the `[u8; N]` lowering the 256-bit and address types use), and
//! the `Int8`/`Int16` leaves the enums serialize through. What RowBinary does
//! not have is a *per-column-type* writer; it is driven by the row struct,
//! so the exotic corpus adds arms rather than a structure. Counting a fourth
//! encoder case for those arms would match the wall-time sibling case for
//! case, which this tier does not do; the sibling carries `rowbinary_exotic`
//! and the scheduled comparison runs it.
//!
//! The measured region is a whole chunk, not one row. A ClickHouse insert is a
//! block: per-row work is only meaningful amortised over one, and the Native
//! encoder's `finish_chunk`, which reserves once and lays out every column,
//! is where a large part of its cost lives.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use bytes::BytesMut;
use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use serde::Serialize;
use spate_clickhouse::{ClickHouseEncoder, NativeEncoder, NativeSchema};
use spate_core::checkpoint::AckRef;
use spate_core::deser::Owned;
use spate_core::record::{PartitionId, Record, RecordMeta};
use spate_core::sink::RowEncoder;
use std::hint::black_box;

#[path = "support/rows.rs"]
mod rows;

use rows::{EventRow, ExoticRow, MetricRow, ROWS};

/// A record carrying one row. The ack receiver is leaked rather than dropped
/// so that resolving a batch cannot enqueue on a live channel and make the
/// count depend on how many records a case built. Nothing here resolves a
/// batch anyway, since the encoders never touch the ack, and both the rows
/// and the receiver are built in setup, outside the collected region.
fn record<T>(payload: T) -> Record<T> {
    let (ack, rx) = AckRef::test_pair();
    std::mem::forget(rx);
    Record {
        payload,
        meta: RecordMeta {
            partition: PartitionId(0),
            offset: 0,
            event_time_ms: 0,
            key_hash: None,
        },
        ack,
    }
}

/// One encoder with the rows it encodes and a buffer sized to hold the result,
/// so the measurement is the encoder's work rather than the allocator growing
/// a `BytesMut` under it.
struct Rig<E, T> {
    enc: E,
    records: Vec<Record<T>>,
    buf: BytesMut,
}

/// The measured work: a whole chunk through one encoder.
fn encode_chunk<E, T>(rig: &mut Rig<E, T>)
where
    E: RowEncoder<Owned<T>>,
    T: Send + 'static,
{
    rig.buf.clear();
    for rec in &rig.records {
        rig.enc.encode(black_box(rec), &mut rig.buf).unwrap();
    }
    rig.enc.finish_chunk(&mut rig.buf).unwrap();
    assert!(!rig.buf.is_empty(), "encoder produced no bytes");
}

fn native_rig<T: Serialize + Send + 'static>(
    cols: &[(&str, &str)],
    payloads: Vec<T>,
) -> Rig<NativeEncoder<Owned<T>>, T> {
    let schema = NativeSchema::from_columns(cols).expect("native schema builds");
    Rig {
        enc: NativeEncoder::<Owned<T>>::new(schema),
        records: payloads.into_iter().map(record).collect(),
        buf: BytesMut::with_capacity(1 << 20),
    }
}

fn rowbinary_rig<T: Serialize + Send + 'static>(
    payloads: Vec<T>,
) -> Rig<ClickHouseEncoder<Owned<T>>, T> {
    Rig {
        enc: ClickHouseEncoder::<Owned<T>>::new(),
        records: payloads.into_iter().map(record).collect(),
        buf: BytesMut::with_capacity(1 << 20),
    }
}

fn native_events() -> Rig<NativeEncoder<Owned<EventRow>>, EventRow> {
    native_rig(&rows::event_columns(), rows::events(ROWS))
}

fn native_metrics() -> Rig<NativeEncoder<Owned<MetricRow>>, MetricRow> {
    native_rig(&rows::metric_columns(), rows::metrics(ROWS))
}

fn native_exotic() -> Rig<NativeEncoder<Owned<ExoticRow>>, ExoticRow> {
    native_rig(&rows::exotic_columns(), rows::exotic(ROWS))
}

fn rowbinary_events() -> Rig<ClickHouseEncoder<Owned<EventRow>>, EventRow> {
    rowbinary_rig(rows::events(ROWS))
}

fn rowbinary_metrics() -> Rig<ClickHouseEncoder<Owned<MetricRow>>, MetricRow> {
    rowbinary_rig(rows::metrics(ROWS))
}

// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and freeing a
// thousand rows of owned strings would swamp the encode it is meant to
// measure. A `///` comment is a `#[doc]` attribute, which
// `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::native_events(native_events())]
fn encode_native_events(
    mut rig: Rig<NativeEncoder<Owned<EventRow>>, EventRow>,
) -> Rig<NativeEncoder<Owned<EventRow>>, EventRow> {
    encode_chunk(&mut rig);
    rig
}

#[library_benchmark]
#[bench::native_metrics(native_metrics())]
fn encode_native_metrics(
    mut rig: Rig<NativeEncoder<Owned<MetricRow>>, MetricRow>,
) -> Rig<NativeEncoder<Owned<MetricRow>>, MetricRow> {
    encode_chunk(&mut rig);
    rig
}

#[library_benchmark]
#[bench::native_exotic(native_exotic())]
fn encode_native_exotic(
    mut rig: Rig<NativeEncoder<Owned<ExoticRow>>, ExoticRow>,
) -> Rig<NativeEncoder<Owned<ExoticRow>>, ExoticRow> {
    encode_chunk(&mut rig);
    rig
}

#[library_benchmark]
#[bench::rowbinary_events(rowbinary_events())]
fn encode_rowbinary_events(
    mut rig: Rig<ClickHouseEncoder<Owned<EventRow>>, EventRow>,
) -> Rig<ClickHouseEncoder<Owned<EventRow>>, EventRow> {
    encode_chunk(&mut rig);
    rig
}

#[library_benchmark]
#[bench::rowbinary_metrics(rowbinary_metrics())]
fn encode_rowbinary_metrics(
    mut rig: Rig<ClickHouseEncoder<Owned<MetricRow>>, MetricRow>,
) -> Rig<ClickHouseEncoder<Owned<MetricRow>>, MetricRow> {
    encode_chunk(&mut rig);
    rig
}

library_benchmark_group!(
    name = encode;
    benchmarks =
        encode_native_events,
        encode_native_metrics,
        encode_native_exotic,
        encode_rowbinary_events,
        encode_rowbinary_metrics
);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation, and so every `Ir` baseline, is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the encode under measurement rather than to
// whichever frame the default depth of 4 happens to cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = encode
);
