//! Instruction counts for Distributed-parity shard routing (gungraun).
//!
//! One shape — route a run of records through
//! [`DistributedRouter`](spate_clickhouse::DistributedRouter), exactly as the
//! shard-affinity terminal stage does before anything is batched —
//! parameterised by the sharding key's type and the cluster's weights.
//!
//! Routing sits ahead of every other per-record cost in this sink: a record
//! is hashed and placed before it reaches an encoder, so the count here is
//! paid whether or not the batch it joins is ever written. The work is
//! allocation-free and fully deterministic, which makes it exactly the kind
//! of hot path an instruction count describes better than a wall clock — the
//! numbers are tens of nanoseconds, small enough that timer resolution and
//! frequency scaling dominate a measured duration.
//!
//! The cases cover the two axes that decide the cost. The **key** decides how
//! much the hash digests: `str_short` and `str_long` sit either side of
//! XXH64's 32-byte regime change, `blob` is a pre-encoded binary key, and the
//! two integer cases hash a key column at its declared width — four bytes for
//! `UInt32`, eight for `UInt64`, a distinction Distributed parity depends on.
//! The **weights** decide which half of `shard_for_hash` runs: `uniform` is
//! the all-weights-1 fast path that reduces to `hash % N`, and `tiered` is
//! the interval scan a heterogeneous cluster takes.
//!
//! Deliberately absent is a case per `ShardKey` variant at matched length,
//! and a weight pair for every key. `Str` and `Bytes` hash the same bytes
//! through the same call — the variant is a match arm, not a code path — so a
//! short `Str` against a 16-byte `Bytes` covers both variants and a third
//! length at once. The weight axis is orthogonal to the key, so one pair of
//! cases at a shared key measures it: six cases, not sixteen. Callgrind runs
//! under emulation, and a case that only re-measures a combination two others
//! already fix costs real time on every pull request.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use spate_clickhouse::{DistributedRouter, ShardKey};
use spate_core::checkpoint::AckRef;
use spate_core::deser::Owned;
use spate_core::record::{PartitionId, Record, RecordMeta};
use spate_core::sink::RecordRouter;
use std::hint::black_box;

#[path = "support/keys.rs"]
mod keys;

use keys::{KEYS, TIERED, UNIFORM};

/// One router with the records it routes.
struct Rig<T: Send + 'static> {
    router: DistributedRouter<Owned<T>>,
    records: Vec<Record<T>>,
}

/// The measured work: a run of records placed on shards.
///
/// The shard count is re-read inside the loop rather than hoisted, because
/// that is what the terminal stage does — it passes its own `shards.len()` on
/// every call, and the router asserts the two agree per record. It buys
/// fidelity of shape, not a different number: both spellings were measured,
/// and all six cases counted bit-identically either way.
///
/// Summing the shard indices is what keeps the loop alive: the routing
/// decision is otherwise unobserved, and without a use the optimiser is free
/// to delete the call this exists to count.
fn route_all<T: Send + 'static>(rig: &Rig<T>) -> usize {
    let mut acc = 0usize;
    for rec in &rig.records {
        acc += rig
            .router
            .route_record(black_box(rec), rig.router.shard_count());
    }
    assert!(acc > 0, "every record routed to shard 0");
    acc
}

/// Records sharing one ack.
///
/// The encoder bench gives every record its own [`AckRef::test_pair`]; at
/// this record count that would be a hundred thousand live channels built in
/// setup, so these clone a single ref instead. Nothing routes an
/// acknowledgement — the router never touches the ack — and the receiver is
/// leaked rather than dropped so that a resolved batch could not enqueue on a
/// live channel and make the count depend on how many records a case built.
fn records<T>(payloads: Vec<T>) -> Vec<Record<T>> {
    let (ack, rx) = AckRef::test_pair();
    std::mem::forget(rx);
    payloads
        .into_iter()
        .enumerate()
        .map(|(i, payload)| Record {
            payload,
            meta: RecordMeta {
                partition: PartitionId(0),
                offset: i as i64,
                event_time_ms: 0,
                key_hash: None,
            },
            ack: ack.clone(),
        })
        .collect()
}

fn rig<T: Send + 'static>(router: DistributedRouter<Owned<T>>, payloads: Vec<T>) -> Rig<T> {
    Rig {
        router,
        records: records(payloads),
    }
}

// A `KeyExtractor` is a plain fn pointer over the `Rec<'buf>` GAT, so each of
// these must take the family's owned record type by reference — `&String`,
// not `&str` — for the coercion to hold. That is what `clippy::ptr_arg` sees.
//
// The routers are built here rather than by a generic helper for the same
// reason: `<Owned<T> as RecFamily>::Rec<'buf>` only normalizes to `T` once `T`
// is a concrete type, so a helper taking a `KeyExtractor<Owned<T>>` never
// type-checks against a plain `fn(&T) -> ShardKey<'_>`.
#[allow(
    clippy::ptr_arg,
    reason = "the KeyExtractor fn-pointer signature fixes the argument type"
)]
fn str_key(rec: &String) -> ShardKey<'_> {
    ShardKey::Str(rec)
}

#[allow(
    clippy::ptr_arg,
    reason = "the KeyExtractor fn-pointer signature fixes the argument type"
)]
fn blob_key(rec: &Vec<u8>) -> ShardKey<'_> {
    ShardKey::Bytes(rec)
}

fn u64_key(rec: &u64) -> ShardKey<'_> {
    ShardKey::U64(*rec)
}

fn u32_key(rec: &u32) -> ShardKey<'_> {
    ShardKey::U32(*rec)
}

fn str_router(weights: &[u32]) -> DistributedRouter<Owned<String>> {
    DistributedRouter::<Owned<String>>::new(str_key, weights).expect("weights are valid")
}

fn str_short_uniform() -> Rig<String> {
    rig(str_router(&UNIFORM), keys::short_strings(KEYS))
}

fn str_long_uniform() -> Rig<String> {
    rig(str_router(&UNIFORM), keys::long_strings(KEYS))
}

fn str_short_tiered() -> Rig<String> {
    rig(str_router(&TIERED), keys::short_strings(KEYS))
}

fn blob_uniform() -> Rig<Vec<u8>> {
    rig(
        DistributedRouter::<Owned<Vec<u8>>>::new(blob_key, &UNIFORM).expect("weights are valid"),
        keys::blobs(KEYS),
    )
}

fn u64_uniform() -> Rig<u64> {
    rig(
        DistributedRouter::<Owned<u64>>::new(u64_key, &UNIFORM).expect("weights are valid"),
        keys::u64s(KEYS),
    )
}

fn u32_uniform() -> Rig<u32> {
    rig(
        DistributedRouter::<Owned<u32>>::new(u32_key, &UNIFORM).expect("weights are valid"),
        keys::u32s(KEYS),
    )
}

// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and freeing a
// hundred thousand records would swamp the routing it is meant to measure. A
// `///` comment is a `#[doc]` attribute, which `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::str_short_uniform(str_short_uniform())]
#[bench::str_long_uniform(str_long_uniform())]
#[bench::str_short_tiered(str_short_tiered())]
fn route_strings(rig: Rig<String>) -> (usize, Rig<String>) {
    (route_all(&rig), rig)
}

#[library_benchmark]
#[bench::blob_uniform(blob_uniform())]
fn route_blobs(rig: Rig<Vec<u8>>) -> (usize, Rig<Vec<u8>>) {
    (route_all(&rig), rig)
}

#[library_benchmark]
#[bench::u64_uniform(u64_uniform())]
fn route_u64(rig: Rig<u64>) -> (usize, Rig<u64>) {
    (route_all(&rig), rig)
}

#[library_benchmark]
#[bench::u32_uniform(u32_uniform())]
fn route_u32(rig: Rig<u32>) -> (usize, Rig<u32>) {
    (route_all(&rig), rig)
}

library_benchmark_group!(
    name = route;
    benchmarks = route_strings, route_blobs, route_u64, route_u32
);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the routing under measurement rather than to
// whichever frame the default depth of 4 happens to cut at. Routing itself
// allocates nothing, which is the point: the profile is the assertion.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = route
);
