//! Instruction counts for the record-to-message encode path (gungraun).
//!
//! One shape — drive a run of records through
//! [`KafkaEncoder`](spate_kafka::sink::KafkaEncoder), exactly as the sink's
//! terminal stage does between seals — parameterized by the message encoder
//! underneath it and by the shape of the message that comes out.
//!
//! This is the pipeline-thread half of the sink: the message encoder fills
//! the reusable accumulator, the adapter sums the guarded size, and the
//! connector's internal frame writer appends one length-delimited entry. The
//! frame writer is private and stays private — it is measured because
//! `KafkaEncoder::encode` calls it, not because anything was widened to reach
//! it.
//!
//! It is not the sink's whole per-record cost, and reading it as one would be
//! a mistake. On the other side of the queue a shard worker parses every frame
//! back into messages and rebuilds a header list per message before librdkafka
//! sees anything, and that half is unmeasured: it lives inside an async
//! `write_batch`, which is the shape this instrument cannot enter. A
//! regression there moves sink CPU without moving any number below.
//!
//! The cases cover the axes that decide the cost — which encoder fills the
//! accumulator, which parts of a message it fills, and whether the size guard
//! lets the result through:
//!
//! - `bytes_keyless` — payload passthrough, no key, no headers. The floor
//!   every record pays: clear the accumulator, copy the payload in, copy it
//!   back out into the frame. The denominator the rest are read against.
//! - `bytes_keyed` — the same corpus with a payload-derived key. The delta
//!   against `bytes_keyless` is the key's own cost: a second copy into the
//!   accumulator, a longer guarded size, and one more framed section.
//! - `stamped_headers` — the same corpus plus the four provenance headers a
//!   Kafka-to-Kafka hop carries. Headers are the one part of a message whose
//!   cost scales with a count rather than with a buffer length: the guard sums
//!   a name and a value per header, and the frame writes two length-delimited
//!   sections for each.
//! - `stamped_over_limit` — that case's one variable changed. The
//!   `max_message_bytes` limit is set to exactly the payload length, so the
//!   payload alone would pass and the headers push every record over. Nothing
//!   is framed; the count is the size guard's rejection path, which builds a
//!   formatted diagnostic per record and is therefore far from free. It is the
//!   path a stream of oversized records under the default Skip policy actually
//!   runs, and the only case here that produces no bytes.
//! - `json_typed` — a flat typed struct through `serde_json`, sized so its
//!   documents land near the passthrough payload length. Serialization
//!   dominates, which is the point: read against `bytes_keyless` it says what
//!   fraction of a JSON sink's per-record cost the connector's own accumulator
//!   and framing are.
//!
//! The matrix is deliberately sparse. The key axis is exercised once, on the
//! passthrough encoder, where it stands out against a small denominator
//! instead of disappearing into serialization; the guard axis is exercised
//! once, on the header case, because header bytes are what make this guard
//! differ from librdkafka's key-plus-payload check. Callgrind runs under
//! emulation, and a case that only re-measures a combination two others
//! already fix costs real time on every pull request.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use bytes::BytesMut;
use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use spate_core::checkpoint::AckRef;
use spate_core::deser::Owned;
use spate_core::record::{PartitionId, Record, RecordMeta};
use spate_core::sink::RowEncoder;
use spate_kafka::sink::{KafkaBytesEncoder, KafkaEncoder, KafkaJsonEncoder, MessageEncoder};
use std::hint::black_box;

#[path = "support/messages.rs"]
mod messages;

use messages::{Event, HeaderStamp, RECORDS};

/// One encoder with the records it encodes and a buffer sized to hold the
/// result, so the measurement is the encode path's work rather than the
/// allocator growing a `BytesMut` under it.
struct Rig<T: Send + 'static, M> {
    enc: KafkaEncoder<Owned<T>, M>,
    records: Vec<Record<T>>,
    buf: BytesMut,
}

/// The measured work: a run of records through one encoder, returning how many
/// were accepted.
///
/// `#[inline(never)]` is load-bearing, not stylistic, and removing it does not
/// fail anything — it silently empties the measurement. Callgrind toggles
/// collection on the benchmark function, and `KafkaEncoder::encode` is generic
/// over both the record family and the message encoder, so it monomorphises
/// into *this* crate and is an ordinary inlining candidate. Without a frame
/// the optimizer may not erase, the loop is reshaped across the toggle
/// boundary and the region no longer contains the work: dropping the attribute
/// takes `bytes_keyless` from 3,500,338 instructions to **22**, and three of
/// the other four cases with it, while every one of them still runs and still
/// reports a number.
///
/// Counting the accepted records is what keeps the loop alive: every case's
/// output is otherwise unobserved, and without a use the optimizer is free to
/// delete the call this exists to count. The caller asserts the count, so a
/// case that silently stopped encoding — or started failing — cannot pass as a
/// fast one.
#[inline(never)]
fn encode_run<T, M>(rig: &mut Rig<T, M>) -> usize
where
    T: Send + 'static,
    M: MessageEncoder<Owned<T>>,
{
    rig.buf.clear();
    let mut accepted = 0usize;
    for rec in &rig.records {
        if rig.enc.encode(black_box(rec), &mut rig.buf).is_ok() {
            accepted += 1;
        }
    }
    accepted
}

/// Records sharing one ack.
///
/// One `AckRef` cloned across the corpus rather than one per record: at this
/// record count a pair each would be ten thousand live channels built in
/// setup. Nothing on this path touches an acknowledgment — the encoder never
/// resolves one — so the only traffic is the single message the last handle
/// sends as it drops, and leaking the receiver keeps the channel connected so
/// that send is delivered rather than discarded. Either way it costs the
/// measurement nothing: the rig is returned rather than dropped, so the drop
/// happens at teardown, outside the collected region.
fn records<T>(payloads: Vec<T>) -> Vec<Record<T>> {
    let (ack, rx) = AckRef::test_pair();
    std::mem::forget(rx);
    payloads
        .into_iter()
        .enumerate()
        .map(|(i, payload)| Record {
            payload,
            meta: RecordMeta {
                partition: PartitionId(0),
                offset: i as i64,
                event_time_ms: 0,
                key_hash: None,
            },
            ack: ack.clone(),
        })
        .collect()
}

/// A rig whose buffer already holds the run, so no case measures a `BytesMut`
/// doubling its way up to the frame size.
fn rig<T: Send + 'static, M>(enc: KafkaEncoder<Owned<T>, M>, payloads: Vec<T>) -> Rig<T, M> {
    Rig {
        enc,
        records: records(payloads),
        buf: BytesMut::with_capacity(16 << 20),
    }
}

fn bytes_keyless() -> Rig<Vec<u8>, KafkaBytesEncoder> {
    rig(
        KafkaEncoder::new(KafkaBytesEncoder::new()),
        messages::payloads(RECORDS),
    )
}

fn bytes_keyed() -> Rig<Vec<u8>, KafkaBytesEncoder> {
    rig(
        KafkaEncoder::new(KafkaBytesEncoder::with_key_fn(messages::key_prefix)),
        messages::payloads(RECORDS),
    )
}

fn stamped_headers() -> Rig<Vec<u8>, HeaderStamp> {
    rig(KafkaEncoder::new(HeaderStamp), messages::payloads(RECORDS))
}

/// The same stamped messages under a limit the headers push them past.
fn stamped_over_limit() -> Rig<Vec<u8>, HeaderStamp> {
    rig(
        KafkaEncoder::with_max_message_bytes(HeaderStamp, messages::GUARD_LIMIT),
        messages::payloads(RECORDS),
    )
}

fn json_typed() -> Rig<Event, KafkaJsonEncoder<Owned<Event>>> {
    rig(
        KafkaEncoder::new(KafkaJsonEncoder::<Owned<Event>>::new()),
        messages::events(RECORDS),
    )
}

// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and freeing ten
// thousand records and a multi-megabyte frame would swamp the encoding it is
// meant to measure. A `///` comment is a `#[doc]` attribute, which
// `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::bytes_keyless(bytes_keyless())]
#[bench::bytes_keyed(bytes_keyed())]
fn encode_bytes(mut rig: Rig<Vec<u8>, KafkaBytesEncoder>) -> Rig<Vec<u8>, KafkaBytesEncoder> {
    assert_eq!(encode_run(&mut rig), RECORDS, "a record failed to encode");
    assert!(!rig.buf.is_empty(), "the encoder produced no bytes");
    rig
}

#[library_benchmark]
#[bench::stamped_headers(stamped_headers())]
fn encode_stamped(mut rig: Rig<Vec<u8>, HeaderStamp>) -> Rig<Vec<u8>, HeaderStamp> {
    assert_eq!(encode_run(&mut rig), RECORDS, "a record failed to encode");
    assert!(!rig.buf.is_empty(), "the encoder produced no bytes");
    rig
}

// The rejection path. Asserting that *nothing* was accepted is what stops this
// silently becoming a second copy of `stamped_headers`: a limit raised out of
// reach, or a guard that stopped counting header bytes, would leave a case
// that still ran and still produced a number.
#[library_benchmark]
#[bench::stamped_over_limit(stamped_over_limit())]
fn reject_oversized(mut rig: Rig<Vec<u8>, HeaderStamp>) -> Rig<Vec<u8>, HeaderStamp> {
    assert_eq!(encode_run(&mut rig), 0, "the size guard accepted a record");
    assert!(rig.buf.is_empty(), "a rejected record was still framed");
    rig
}

#[library_benchmark]
#[bench::json_typed(json_typed())]
fn encode_json(
    mut rig: Rig<Event, KafkaJsonEncoder<Owned<Event>>>,
) -> Rig<Event, KafkaJsonEncoder<Owned<Event>>> {
    assert_eq!(encode_run(&mut rig), RECORDS, "a record failed to encode");
    assert!(!rig.buf.is_empty(), "the encoder produced no bytes");
    rig
}

library_benchmark_group!(
    name = encode;
    benchmarks = encode_bytes, encode_stamped, reject_oversized, encode_json
);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the encode under measurement rather than to
// whichever frame the default depth of 4 happens to cut at. The passthrough
// cases should allocate nothing at all in steady state, which is a claim the
// profile can settle.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = encode
);
