//! Instruction counts for the Avro decode paths (gungraun).
//!
//! A subset of what `benches/decode.rs` times, counted instead of timed:
//! callgrind's instruction count is deterministic, so it compares across the
//! shared CI runners where a wall-clock number is only noise. DHAT runs
//! alongside callgrind in the same invocation, so every case also reports
//! deterministic heap counts — allocated blocks, bytes, and the t-gmax peak.
//! Six cases, not the full criterion matrix — callgrind runs the workload
//! under emulation, and the published comparison corpus (200 batches, 20,000
//! events per iteration) is far too large to emulate.
//!
//! What the six cases are for:
//!
//! - `flat_record` × `value` / `serde_typed` / `datum_typed` — the three
//!   decode paths over one 15-field record. This is the comparison the crate
//!   exists to settle, and instructions attribute it without a timer; the
//!   heap counts attribute the `Value`-tree allocations that separate the
//!   dynamically-typed path from the single-pass one.
//! - `batch50` × `value` / `datum_typed` — the same two ends of that spread
//!   over an array-shaped record, where the dynamically-typed path's
//!   per-element allocation concentrates. The serde arm is left out because
//!   it sits between the two and moves with them.
//! - `flat_record_malformed` × `value` — the flat record truncated
//!   mid-field. Skip and Fail both pay decode-until-error plus the `Err`
//!   for every bad record (INV-7 admits no other policy), so this count is
//!   the per-record price of a poison-pill storm.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use spate_avro::{
    AvroDatumDeserializer, AvroDeserializerBuilder, AvroMode, AvroSerdeDeserializer, AvroSettings,
    AvroValueDeserializer, SchemaSource,
};
use spate_core::checkpoint::AckRef;
use spate_core::deser::{Deserializer, Owned, RecFamily};
use spate_core::record::{PartitionId, RawPayload};
use std::hint::black_box;

#[path = "support/orders.rs"]
mod orders;

use orders::Sink;

/// One deserializer with the bytes it decodes.
///
/// The payload is owned rather than pre-wrapped in a `RawPayload`, because a
/// `RawPayload` borrows it and a benchmark argument has to be a single owned
/// value. Building the wrapper is a handful of stores inside the measured
/// region; it is identical across the cases, so it cancels in any comparison.
struct Rig<D> {
    deser: D,
    payload: Vec<u8>,
    ack: AckRef,
    sink: Sink,
    // The builder keeps this runtime's handle for the registry fetcher. Raw
    // mode never uses it, but the handle must not outlive the runtime.
    _rt: tokio::runtime::Runtime,
}

/// A free function rather than a `Rig` method: borrowing the whole rig would
/// collide with the mutable borrows of `deser` and `sink`.
fn raw_payload(bytes: &[u8]) -> RawPayload<'_> {
    RawPayload {
        bytes,
        key: None,
        partition: PartitionId(0),
        offset: 1,
        timestamp_ms: 0,
    }
}

/// The measured work: one payload through one deserializer.
fn decode_once<F, D>(rig: &mut Rig<D>)
where
    F: RecFamily,
    D: Deserializer<F>,
{
    let raw = raw_payload(&rig.payload);
    rig.deser
        .deserialize(black_box(&raw), &rig.ack, &mut rig.sink)
        .unwrap();
}

/// The measured error path: one malformed payload through one deserializer.
/// The stage applies the `ErrorPolicy` after `deserialize` returns, so
/// decode-until-error plus building the `Err` is the cost shared by Skip and
/// Fail. The assert mirrors `decode_once`'s `unwrap`: if the fixture ever
/// decodes cleanly, the bench panics instead of quietly counting the happy
/// path.
fn decode_once_err<F, D>(rig: &mut Rig<D>)
where
    F: RecFamily,
    D: Deserializer<F>,
{
    let raw = raw_payload(&rig.payload);
    let res = rig
        .deser
        .deserialize(black_box(&raw), &rig.ack, &mut rig.sink);
    assert!(black_box(res).is_err(), "malformed fixture decoded cleanly");
}

/// Build a builder over a fixed inline schema in raw mode — no registry, so
/// nothing in the measured path touches the network.
fn rig<D>(
    schema: &str,
    payload: Vec<u8>,
    build: impl FnOnce(&AvroDeserializerBuilder) -> D,
) -> Rig<D> {
    let settings = AvroSettings {
        mode: AvroMode::Raw,
        schema: Some(SchemaSource::inline(schema)),
        ..AvroSettings::default()
    };
    let rt = tokio::runtime::Builder::new_current_thread()
        .build()
        .unwrap();
    let builder = AvroDeserializerBuilder::from_settings(&settings, rt.handle()).unwrap();
    let deser = build(&builder);
    // The rig holds the only `AckRef`, so the batch never resolves and no
    // message is ever sent — the receiver has nothing to keep alive.
    let (ack, _ack_rx) = AckRef::test_pair();
    Rig {
        deser,
        payload,
        ack,
        sink: Sink(0),
        _rt: rt,
    }
}

fn flat_value_rig() -> Rig<AvroValueDeserializer> {
    rig(orders::SCHEMA, orders::order_datum(), |b| {
        b.build_value().expect("value builder")
    })
}

fn flat_serde_rig() -> Rig<AvroSerdeDeserializer<orders::Order>> {
    rig(orders::SCHEMA, orders::order_datum(), |b| {
        b.build_serde::<orders::Order>().expect("serde builder")
    })
}

fn flat_datum_rig() -> Rig<AvroDatumDeserializer<Owned<orders::Order>>> {
    rig(orders::SCHEMA, orders::order_datum(), |b| {
        b.build_serde_datum::<orders::Order>()
            .expect("datum builder")
    })
}

fn flat_value_malformed_rig() -> Rig<AvroValueDeserializer> {
    rig(orders::SCHEMA, orders::malformed_datum(), |b| {
        b.build_value().expect("value builder")
    })
}

fn batch_value_rig() -> Rig<AvroValueDeserializer> {
    rig(orders::BATCH_SCHEMA, orders::batch_datum(), |b| {
        b.build_value().expect("value builder")
    })
}

fn batch_datum_rig() -> Rig<AvroDatumDeserializer<Owned<orders::SensorBatch>>> {
    rig(orders::BATCH_SCHEMA, orders::batch_datum(), |b| {
        b.build_serde_datum::<orders::SensorBatch>()
            .expect("datum builder")
    })
}

// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and tearing down
// a runtime would swamp the decode it is meant to measure. A `///` comment is
// a `#[doc]` attribute, which `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::flat_record(flat_value_rig())]
#[bench::batch50(batch_value_rig())]
fn decode_value(mut rig: Rig<AvroValueDeserializer>) -> Rig<AvroValueDeserializer> {
    decode_once(&mut rig);
    rig
}

#[library_benchmark]
#[bench::flat_record(flat_serde_rig())]
fn decode_serde_typed(
    mut rig: Rig<AvroSerdeDeserializer<orders::Order>>,
) -> Rig<AvroSerdeDeserializer<orders::Order>> {
    decode_once(&mut rig);
    rig
}

#[library_benchmark]
#[bench::flat_record(flat_datum_rig())]
fn decode_datum_typed(
    mut rig: Rig<AvroDatumDeserializer<Owned<orders::Order>>>,
) -> Rig<AvroDatumDeserializer<Owned<orders::Order>>> {
    decode_once(&mut rig);
    rig
}

#[library_benchmark]
#[bench::flat_record_malformed(flat_value_malformed_rig())]
fn decode_value_malformed(mut rig: Rig<AvroValueDeserializer>) -> Rig<AvroValueDeserializer> {
    decode_once_err(&mut rig);
    rig
}

#[library_benchmark]
#[bench::batch50(batch_datum_rig())]
fn decode_batch_datum_typed(
    mut rig: Rig<AvroDatumDeserializer<Owned<orders::SensorBatch>>>,
) -> Rig<AvroDatumDeserializer<Owned<orders::SensorBatch>>> {
    decode_once(&mut rig);
    rig
}

library_benchmark_group!(
    name = decode;
    benchmarks =
        decode_value,
        decode_serde_typed,
        decode_datum_typed,
        decode_value_malformed,
        decode_batch_datum_typed
);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough that heap blocks attribute to the decode under measurement
// rather than to whichever frame the default depth of 4 happens to cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = decode
);
