//! Instruction counts for this crate's decode paths (gungraun).
//!
//! The sibling `benches/decode.rs` measures `serde_json` directly — the floor
//! any JSON decoder is read against. These measure **this crate**: the
//! framing the deserializer applies to a payload, the record emission, and the
//! per-record error isolation that comes with it. A regression in
//! `JsonSerdeDeserializer` would not show up in the floor.
//!
//! One shape — one payload through one deserializer — parameterised by the
//! framing the payload carries and the target it decodes into:
//!
//! - `single_typed` / `single_value` — one flat 15-field document, decoded
//!   into a struct and into a dynamically-typed value. The per-record cost
//!   every payload pays, and the two ends of the typing axis.
//! - `ndjson_batch50` — fifty records newline-delimited. This framing isolates
//!   errors per line, so it does per-record bookkeeping the others do not; the
//!   gap against `array_batch50` is what that isolation costs.
//! - `array_batch50` — the same fifty records as one top-level array, decoded
//!   in a single pass and handled atomically on error.
//!
//! The matrix is deliberately sparse. The typing axis is exercised once, on
//! the single-document case, because it moves with the payload rather than
//! with the framing — pairing every framing with every target would add cases
//! that cannot say anything the first two do not.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};
use serde_json::Value;
use spate_core::checkpoint::AckRef;
use spate_core::deser::{Deserializer, Owned, RecFamily};
use spate_core::record::{PartitionId, RawPayload};
use spate_json::{JsonDeserializerBuilder, JsonFraming, JsonSettings, OnError};
use std::hint::black_box;

#[path = "support/orders.rs"]
mod orders;

use orders::{Order, Reading, Sink};

/// The number of records the batch framings carry. Fifty is the same batch
/// size the Avro decode bench uses, so the two are comparable per element.
const BATCH: u64 = 50;

/// One deserializer with the bytes it decodes.
///
/// The payload is owned rather than pre-wrapped in a `RawPayload`, because a
/// `RawPayload` borrows it and a benchmark argument has to be a single owned
/// value. Building the wrapper is a handful of stores inside the measured
/// region; it is identical across the cases, so it cancels in any comparison.
struct Rig<D> {
    deser: D,
    payload: Vec<u8>,
    ack: AckRef,
    sink: Sink,
    /// How many records this payload must yield. Asserted rather than
    /// returned: a framing that silently stopped splitting would otherwise
    /// read as a large improvement.
    expect: u64,
}

fn raw_payload(bytes: &[u8]) -> RawPayload<'_> {
    RawPayload {
        bytes,
        key: None,
        partition: PartitionId(0),
        offset: 1,
        timestamp_ms: 0,
    }
}

/// The measured work: one payload through one deserializer.
fn decode_once<F, D>(rig: &mut Rig<D>)
where
    F: RecFamily,
    D: Deserializer<F>,
{
    let raw = raw_payload(&rig.payload);
    rig.sink.0 = 0;
    rig.deser
        .deserialize(black_box(&raw), &rig.ack, &mut rig.sink)
        .unwrap();
    assert_eq!(rig.sink.0, rig.expect, "framing emitted a different count");
}

fn settings(framing: JsonFraming) -> JsonSettings {
    JsonSettings {
        framing,
        // Skip is the shipped default, so this is the path production takes.
        // It is not the cheaper of the two by construction: on valid input
        // Skip's error bookkeeping never runs, while ndjson under Fail buffers
        // every decoded payload before emitting any of them. Measuring the
        // default is the point; a Fail case would be a second shape, not a
        // stricter version of this one.
        on_error: OnError::Skip,
        // Off: the structural check parses each document a second time, which
        // would measure the guard rather than the decode.
        reject_duplicate_keys: false,
    }
}

fn rig<D>(
    framing: JsonFraming,
    payload: Vec<u8>,
    expect: u64,
    build: impl FnOnce(&JsonDeserializerBuilder) -> D,
) -> Rig<D> {
    let builder = JsonDeserializerBuilder::from_settings(settings(framing));
    let deser = build(&builder);
    // The receiver is dropped here, so when the last `AckRef` goes with the rig
    // the batch resolves into a disconnected channel and the send is discarded.
    // That happens in teardown, outside the collected region, which is why the
    // ack path costs the measurement nothing beyond the per-record clone.
    let (ack, _ack_rx) = AckRef::test_pair();
    Rig {
        deser,
        payload,
        ack,
        sink: Sink(0),
        expect,
    }
}

fn single_typed_rig() -> Rig<spate_json::JsonSerdeDeserializer<Order>> {
    rig(JsonFraming::Single, orders::order_document(), 1, |b| {
        b.build_serde::<Order>()
    })
}

fn single_value_rig() -> Rig<spate_json::JsonValueDeserializer> {
    rig(JsonFraming::Single, orders::order_document(), 1, |b| {
        b.build_value()
    })
}

fn ndjson_batch_rig() -> Rig<spate_json::JsonSerdeDeserializer<Reading>> {
    rig(
        JsonFraming::Ndjson,
        orders::readings_ndjson(BATCH),
        BATCH,
        |b| b.build_serde::<Reading>(),
    )
}

fn array_batch_rig() -> Rig<spate_json::JsonSerdeDeserializer<Reading>> {
    rig(
        JsonFraming::Array,
        orders::readings_array(BATCH),
        BATCH,
        |b| b.build_serde::<Reading>(),
    )
}

// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, which would
// charge the count for tearing the deserializer down. A `///` comment is a
// `#[doc]` attribute, which `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::single_typed(single_typed_rig())]
fn decode_typed(
    mut rig: Rig<spate_json::JsonSerdeDeserializer<Order>>,
) -> Rig<spate_json::JsonSerdeDeserializer<Order>> {
    decode_once::<Owned<Order>, _>(&mut rig);
    rig
}

#[library_benchmark]
#[bench::single_value(single_value_rig())]
fn decode_value(
    mut rig: Rig<spate_json::JsonValueDeserializer>,
) -> Rig<spate_json::JsonValueDeserializer> {
    decode_once::<Owned<Value>, _>(&mut rig);
    rig
}

#[library_benchmark]
#[bench::ndjson_batch50(ndjson_batch_rig())]
#[bench::array_batch50(array_batch_rig())]
fn decode_framed(
    mut rig: Rig<spate_json::JsonSerdeDeserializer<Reading>>,
) -> Rig<spate_json::JsonSerdeDeserializer<Reading>> {
    decode_once::<Owned<Reading>, _>(&mut rig);
    rig
}

library_benchmark_group!(
    name = decode;
    benchmarks = decode_typed, decode_value, decode_framed
);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the decode under measurement rather than to
// whichever frame the default depth of 4 happens to cut at.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = decode
);
