//! Instruction counts for streaming record framing (gungraun).
//!
//! [`NdjsonFramer`] is this crate's [`RecordFramer`]: it cuts a byte *stream*
//! into newline-delimited records so a streaming source can hand the
//! deserializer one document per payload. It is the source-side counterpart to
//! the in-memory `ndjson` framing the decode bench measures, and a different
//! shape of work — chunk-fed and stateful, where the deserializer's split runs
//! over a payload already resident in RAM.
//!
//! The rig itself is `support/frame_rig.rs`, which `framing_wall.rs` also
//! compiles, so the region counted here is the region that tier times.
//!
//! One shape: drive a byte stream through one framer in chunks, popping
//! records as they complete, the way a source's read loop does. What varies is
//! the stream, because the framer knows nothing about JSON beyond the newline
//! convention and so its cost is decided entirely by shape:
//!
//! - `lf_fetch_chunks` — the baseline regime and the denominator for the rest:
//!   many lines per chunk, which is what a fetch-sized read hands the framer.
//! - `lf_line_chunks` — the same bytes with each chunk holding exactly one
//!   line. The stream, the record count and the framed bytes are identical to
//!   the baseline, so the difference is the per-`push` term alone, charged at
//!   the highest rate a whole-line feed can charge it.
//! - `lf_split_chunks` — the same bytes again in chunks far smaller than a
//!   line, so almost every record is assembled across several pushes through
//!   the partial-line buffer. The other end of the same axis, and the regime a
//!   small-read source or a chunked transfer encoding puts the framer in.
//! - `crlf_fetch_chunks` — the baseline stream terminated `\r\n`. The framer
//!   strips exactly one trailing `\r`, so the delta is that strip plus one
//!   more byte to scan per line.
//! - `lf_blank_interleaved` — the baseline stream with a blank line after
//!   every record. A blank line is skipped and consumes no record index, so
//!   this is the cost of recognising and discarding one — the case that says
//!   what a pretty-printed or double-spaced export costs.
//! - `lf_wide_lines` — an eighth as many lines, eight times as wide, so the
//!   byte total is the same. Read against the baseline it separates the
//!   framer's per-byte cost from its per-record cost, which no other pair here
//!   can do.
//!
//! The matrix is deliberately sparse, and the omissions are chunk-size
//! combinations. The three chunk-size cases run one byte-identical stream, and
//! every other case runs the same fetch-sized chunk over a stream that differs
//! in exactly one property — the terminator, the blank lines, or the line
//! width — while framing the same records. The two axes are independent: the
//! chunking decides how many `push` calls carry a given quantity of bytes, and
//! what varies between streams decides what those bytes cost once inside.
//! Pairing every chunk size with every stream would add cases that re-measure
//! the product of two effects each already fixed.
//!
//! Needs valgrind and a same-version `gungraun-runner`, neither of which
//! exists on every developer machine: run it with `make bench-gungraun`.
//!
//! [`RecordFramer`]: spate_core::framing::RecordFramer

// `library_benchmark` and `library_benchmark_group` expand to public modules,
// functions and constants of their own, none of which carry documentation, so
// the workspace's `missing_docs` lint has nothing to bite on here.
#![expect(missing_docs, reason = "items are generated by gungraun macros")]

use gungraun::{Dhat, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main};

#[path = "support/frame_rig.rs"]
mod frame_rig;
#[path = "support/lines.rs"]
mod lines;

use frame_rig::{Rig, frame_stream};
use lines::Eol;

/// A rig over the standard stream, chunked at `chunk_bytes`.
fn standard(eol: Eol, blank_every: usize, chunk_bytes: usize) -> Rig {
    let stream = lines::stream(lines::RECORDS, lines::LINE_BYTES, eol, blank_every);
    Rig {
        chunks: lines::chunks(&stream, chunk_bytes),
        expect_records: lines::RECORDS,
        expect_bytes: lines::expect_bytes(lines::RECORDS, lines::LINE_BYTES),
    }
}

fn lf_fetch_chunks() -> Rig {
    standard(Eol::Lf, 0, lines::FETCH_CHUNK_BYTES)
}

/// One chunk per line: the line plus its single-byte terminator.
fn lf_line_chunks() -> Rig {
    standard(Eol::Lf, 0, lines::LINE_BYTES + 1)
}

fn lf_split_chunks() -> Rig {
    standard(Eol::Lf, 0, lines::SPLIT_CHUNK_BYTES)
}

fn crlf_fetch_chunks() -> Rig {
    standard(Eol::Crlf, 0, lines::FETCH_CHUNK_BYTES)
}

/// A blank line after every record — the densest interleaving there is, which
/// is what makes the delta against `lf_fetch_chunks` a per-blank-line cost
/// rather than a rounding error.
fn lf_blank_interleaved() -> Rig {
    standard(Eol::Lf, 1, lines::FETCH_CHUNK_BYTES)
}

fn lf_wide_lines() -> Rig {
    let stream = lines::stream(lines::WIDE_RECORDS, lines::WIDE_LINE_BYTES, Eol::Lf, 0);
    Rig {
        chunks: lines::chunks(&stream, lines::FETCH_CHUNK_BYTES),
        expect_records: lines::WIDE_RECORDS,
        expect_bytes: lines::expect_bytes(lines::WIDE_RECORDS, lines::WIDE_LINE_BYTES),
    }
}

// Each case returns its rig rather than dropping it: a value moved into the
// benchmark function is dropped inside the collected region, and freeing fifty
// thousand chunk buffers would swamp the framing it is meant to measure. A
// `///` comment is a `#[doc]` attribute, which `#[library_benchmark]` rejects.
#[library_benchmark]
#[bench::lf_fetch_chunks(lf_fetch_chunks())]
#[bench::lf_line_chunks(lf_line_chunks())]
#[bench::lf_split_chunks(lf_split_chunks())]
#[bench::crlf_fetch_chunks(crlf_fetch_chunks())]
#[bench::lf_blank_interleaved(lf_blank_interleaved())]
#[bench::lf_wide_lines(lf_wide_lines())]
fn frame(rig: Rig) -> Rig {
    assert_eq!(
        frame_stream(&rig),
        (rig.expect_records, rig.expect_bytes),
        "the framing changed; if that is intended, the fixture's expectation is \
         the contract being edited"
    );
    rig
}

library_benchmark_group!(name = framing; benchmarks = frame);

// DHAT is scoped as an extra tool rather than a callgrind argument: the
// callgrind invocation — and so every `Ir` baseline — is bit-identical with
// and without it. `--num-callers=500` (the maximum) keeps allocation stacks
// deep enough to attribute to the framing under measurement rather than to
// whichever frame the default depth of 4 happens to cut at. One allocation per
// framed record is the shape to expect here, and the profile can settle it.
main!(
    config = LibraryBenchmarkConfig::default().tool(Dhat::with_args(["--num-callers=500"])),
    library_benchmark_groups = framing
);
