#!/usr/bin/env bash
#
# Generates crates/spate/examples/README.md, and holds it to the tree.
#
# The root README links a reader straight at the examples directory, so what
# they meet there is either a map or an unannotated file listing. It was the
# second. An index fixes that once; keeping it true is the part that needs a
# machine, because the failure is silent — an example nobody can find is
# indistinguishable from an example that does not exist, and no build breaks.
#
# Generated from a block in each example's own header:
#
#   // INDEX-TIER:  getting-started
#   // INDEX-GOAL:  build, drive and assert on a whole pipeline
#   // INDEX-TECH:  no infrastructure
#   // INDEX-NEEDS: nothing
#
# Plain `//` comments, deliberately: they sit outside the `//!` module docs, so
# they never reach docs.rs, and they read the same way as the `ANCHOR:` markers
# already in these files. The `required-features` column is NOT among them — it
# is in the manifest already, and a field duplicating the manifest is a field
# that disagrees with it.
#
# Fields rather than free prose is the whole design. Regenerating from an
# example's narrative commentary would redden this gate on every wording
# change, which is the trap that moved THIRD-PARTY.md's diff check off the
# pull-request path. A wording change to the prose around these four lines
# cannot fail anything; a missing or orphaned entry always does.
#
# Note the tier here is the *reading* tier — where an example sits in the
# guide. It is a different axis from examples.sh's `free`/`infra`, which is
# whether a pull request can run it: `avro_schema_evolution` needs no
# infrastructure and still belongs under production pipelines.
#
# Usage:
#   ./scripts/examples-index.sh --write   # regenerate the file
#   ./scripts/examples-index.sh --check   # fail if it is out of date
#   ./scripts/examples-index.sh --self-test
set -euo pipefail

self_path="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
cd "$(dirname "$0")/.."

PKG_DIR="crates/spate"
MANIFEST="$PKG_DIR/Cargo.toml"
EXAMPLES_DIR="$PKG_DIR/examples"
INDEX="$EXAMPLES_DIR/README.md"

# Reading tiers, in the order they appear in the file.
TIER_SLUGS="getting-started production bounded-jobs operating extending"

tier_heading() {
    case "$1" in
        getting-started) echo "1. Getting started" ;;
        production)      echo "2. Production pipelines" ;;
        bounded-jobs)    echo "3. Bounded jobs and scaling out" ;;
        operating)       echo "4. Operating" ;;
        extending)       echo "5. Extending" ;;
        *)               echo "" ;;
    esac
}

tier_blurb() {
    case "$1" in
        getting-started) echo "No infrastructure. Read them in this order." ;;
        production)      echo "The shapes a real deployment takes." ;;
        bounded-jobs)    echo "Work that finishes, and work shared across instances." ;;
        operating)       echo "What the pipeline tells you, and what it does when something breaks." ;;
        extending)       echo "Writing your own components against the v1 contracts." ;;
        *)               echo "" ;;
    esac
}

# One `INDEX-<FIELD>:` value from an example source. Empty when absent.
index_field() {
    awk -v field="$2" '
        $0 ~ "^//[[:space:]]*INDEX-" field ":" {
            sub("^//[[:space:]]*INDEX-" field ":[[:space:]]*", "")
            sub(/[[:space:]]+$/, "")
            print
            exit
        }
    ' "$1"
}

# `required-features` for one example, rendered for the table.
manifest_features() {
    awk -v want="$1" '
        /^\[\[example\]\]/ { in_ex = 1; name = ""; next }
        /^\[/              { in_ex = 0 }
        in_ex && /^name[[:space:]]*=/ {
            gsub(/^name[[:space:]]*=[[:space:]]*"/, ""); gsub(/".*$/, ""); name = $0
        }
        in_ex && name == want && /^required-features[[:space:]]*=/ {
            gsub(/^required-features[[:space:]]*=[[:space:]]*\[/, "")
            gsub(/\].*$/, ""); gsub(/"/, ""); gsub(/,[[:space:]]*/, ",")
            print; exit
        }
    ' "$MANIFEST"
}

example_names() {
    find "$EXAMPLES_DIR" -maxdepth 1 -name '*.rs' -exec basename {} .rs \; | sort
}

# The examples in one tier, ordered by `INDEX-RANK` (default 50) and then by
# name, so a tier that claims a reading order has one.
tier_members() {
    local name rank
    for name in $(example_names); do
        [[ "$(index_field "$EXAMPLES_DIR/$name.rs" TIER)" == "$1" ]] || continue
        rank="$(index_field "$EXAMPLES_DIR/$name.rs" RANK)"
        [[ -n "$rank" ]] || rank=50
        printf '%03d %s\n' "$rank" "$name"
    done | sort | awk '{ print $2 }'
}

render() {
    local slug name goal tech needs feats heading

    cat <<'HEADER'
<!--
Generated by scripts/examples-index.sh from the INDEX- block in each example's
header. Do not edit by hand: `make check-examples-index` compares this file
against the tree and fails with the command that regenerates it.
-->

# Examples

Runnable pipelines over one stream: a storefront emitting `order_placed`,
`payment_captured` and `refund_issued`. Every example decodes those same
records, so moving between them costs you a connector, never a domain.

New here, read the three in [Getting started](#1-getting-started) in order.
Otherwise pick the tier matching what you are trying to do — nothing outside
that first tier depends on reading order.

## Running one

```sh
cargo run -p spate --example memory_pipeline
cargo run --release -p spate --features full --example kafka_avro_to_clickhouse
```

An example whose **Features** column is not `—` needs those features on the
command line. Without them cargo reports `no example target named …`, which
reads like a typo rather than a missing flag — cargo skips a target whose
features are unmet rather than complaining about it.

Examples that talk to real servers ship no `docker-compose`. Each one's header
comment names exactly what it needs and which environment variables point at
it, and every shipped config reads its endpoints through `${VAR:-default}`, so
the file you run against your own servers is the file in this directory.

Configuration comes from `SPATE_CONFIG` where an example loads YAML from disk:

```sh
SPATE_CONFIG=/etc/spate/pipeline.yaml cargo run --release -p spate \
  --features full --example kafka_avro_to_clickhouse
```

## The storefront stream

```text
order_placed     { order_id, customer_id, region, placed_at, lines: [{ sku, qty, unit_cents }] }
payment_captured { order_id, amount_cents }
refund_issued    { order_id, amount_cents, reason }
```

The nested `lines` array is what `flat_map` fans out; `customer_id` is what
sharding keys on; the three event kinds are what a split terminal separates.
The types are `spate_datagen::storefront`, so an example and your own code can
share them.

HEADER

    for slug in $TIER_SLUGS; do
        heading="$(tier_heading "$slug")"
        printf '## %s\n\n%s\n\n' "$heading" "$(tier_blurb "$slug")"
        printf '| Example | What it shows | Features | Needs |\n'
        printf '|---|---|---|---|\n'
        # Sorted by rank, then by name. Rank is what lets the first tier say
        # "read them in this order" and mean it; everywhere else it is absent
        # and the tier falls back to alphabetical, which is a stable order
        # rather than a meaningful one.
        for name in $(tier_members "$slug"); do
            goal="$(index_field "$EXAMPLES_DIR/$name.rs" GOAL)"
            tech="$(index_field "$EXAMPLES_DIR/$name.rs" TECH)"
            needs="$(index_field "$EXAMPLES_DIR/$name.rs" NEEDS)"
            feats="$(manifest_features "$name")"
            if [[ -n "$feats" ]]; then
                feats='`'"$feats"'`'
            else
                feats="—"
            fi
            # The backticks in the format string are markdown, not command
            # substitution — the format is single-quoted precisely so nothing
            # in it expands.
            # shellcheck disable=SC2016
            printf '| [`%s`](%s.rs) | How to %s with **%s** | %s | %s |\n' \
                "$name" "$name" "$goal" "$tech" "$feats" "$needs"
        done
        printf '\n'
    done

    cat <<'FOOTER'
## Containers

[`examples/docker`](../../../examples/docker) builds the flagship example into a
distroless image, and its README covers probes, drain timeouts and sizing.

## Related

- [User guide](https://spate.kainth.dev/docs/user-guide/) — the concepts these
  examples are worked instances of
- [`spate` on docs.rs](https://docs.rs/spate) — every type and feature named here
- [`spate-test`](https://docs.rs/spate-test) — the in-memory source and sink the
  infrastructure-free examples are built on
FOOTER
}

run_check() {
    local tmp rc name missing=0

    # Every example must declare all four fields, or its row renders blank and
    # the diff below would happily accept it.
    for name in $(example_names); do
        for field in TIER GOAL TECH NEEDS; do
            if [[ -z "$(index_field "$EXAMPLES_DIR/$name.rs" "$field")" ]]; then
                echo "::error::examples-index.sh: $EXAMPLES_DIR/$name.rs has no \`// INDEX-$field:\` line" >&2
                missing=1
            fi
        done
        if [[ -z "$(tier_heading "$(index_field "$EXAMPLES_DIR/$name.rs" TIER)")" ]]; then
            echo "::error::examples-index.sh: $name declares an unknown INDEX-TIER; known tiers are $TIER_SLUGS" >&2
            missing=1
        fi
    done
    [[ "$missing" -eq 0 ]] || exit 1

    if [[ ! -f "$INDEX" ]]; then
        echo "::error::examples-index.sh: $INDEX does not exist; run \`make examples-index\`" >&2
        exit 1
    fi

    tmp="$(mktemp)"
    render > "$tmp"
    rc=0
    diff -u "$INDEX" "$tmp" || rc=$?
    rm -f "$tmp"
    if [[ "$rc" -ne 0 ]]; then
        echo "::error::examples-index.sh: $INDEX is out of date; run \`make examples-index\`" >&2
        exit 1
    fi
    echo "examples-index.sh: $INDEX matches the tree."
}

run_write() {
    local tmp
    tmp="$(mktemp)"
    render > "$tmp"
    mv "$tmp" "$INDEX"
    echo "examples-index.sh: wrote $INDEX."
}

run_self_test() {
    local tmp rc out
    tmp="$(mktemp -d)"
    cat > "$tmp/ex.rs" <<'FIXTURE'
//! Module docs, which must not be read as index fields.
//!
//! INDEX-GOAL: this line is inside the module docs and must be ignored

// INDEX-TIER:  operating
// INDEX-GOAL:  count what an operator you wrote is doing
// INDEX-TECH:  no infrastructure
// INDEX-NEEDS: nothing
fn main() {}
FIXTURE

    out="$(index_field "$tmp/ex.rs" TIER)/$(index_field "$tmp/ex.rs" NEEDS)"
    if [[ "$out" != "operating/nothing" ]]; then
        rm -rf "$tmp"
        echo "::error::examples-index.sh --self-test: index_field parsed '$out'" >&2
        return 1
    fi

    # A `//!` line must not satisfy a field: the module docs are prose and
    # would otherwise silently win, since they come first in the file.
    out="$(index_field "$tmp/ex.rs" GOAL)"
    if [[ "$out" != "count what an operator you wrote is doing" ]]; then
        rm -rf "$tmp"
        echo "::error::examples-index.sh --self-test: a //! line was read as a field: '$out'" >&2
        return 1
    fi

    out="$(index_field "$tmp/ex.rs" ABSENT)"
    if [[ -n "$out" ]]; then
        rm -rf "$tmp"
        echo "::error::examples-index.sh --self-test: an absent field parsed '$out'" >&2
        return 1
    fi
    rm -rf "$tmp"

    rc=0
    "$self_path" --check > /dev/null 2>&1 || rc=$?
    if [[ "$rc" -ne 0 ]]; then
        echo "::error::examples-index.sh --self-test: --check on the live tree exited $rc" >&2
        return 1
    fi

    echo "examples-index.sh: self-test passed."
}

case "${1:---check}" in
    --check) run_check ;;
    --write) run_write ;;
    --self-test) run_self_test ;;
    *)
        echo "usage: $0 [--check|--write|--self-test]" >&2
        exit 2
        ;;
esac
