import type { Config, PluginConfig } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import { themes as prismThemes } from 'prism-react-renderer';

// The site is deployed to Cloudflare Pages on a dedicated subdomain:
// https://etl-rs.pages.kainth.net/ (Direct Upload from CI — see docs.yml).
// organizationName/projectName below still drive the GitHub source links
// (githubUrl, editUrl, footer), not the deployed URL.
const organizationName = 'MarcusKainth';
const projectName = 'etl-rs';
const githubUrl = `https://github.com/${organizationName}/${projectName}`;

// The old page published at /docs/BENCHMARKS; the tree now lives at
// /docs/benchmarks. plugin-client-redirects writes `<from>/index.html` AFTER the
// build (i.e. build/docs/BENCHMARKS/index.html). On a case-INSENSITIVE filesystem
// (macOS APFS, dev laptops) that path IS build/docs/benchmarks/index.html, so the
// stub clobbers the real Benchmarks landing page. The deploy runs on ubuntu-latest
// (case-sensitive), where BENCHMARKS/ and benchmarks/ coexist, so register the
// redirect only in CI. Local builds drop the stub — fine, it exists solely to keep
// old published /docs/BENCHMARKS links alive.
const benchmarksRedirect: PluginConfig = [
  '@docusaurus/plugin-client-redirects',
  {
    redirects: [{ from: '/docs/BENCHMARKS', to: '/docs/benchmarks' }],
  },
];

const config: Config = {
  title: 'etl-rs',
  tagline: 'High-performance, at-least-once ETL pipelines in Rust',
  favicon: 'img/favicon.svg',

  url: 'https://etl-rs.pages.kainth.net',
  baseUrl: '/',
  organizationName,
  projectName,
  trailingSlash: false,

  // Broken internal links fail the build — a content-hygiene gate that keeps
  // CI honest as docs change. Anchors stay lenient (cross-doc heading links
  // are easy to trip on and low-risk).
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
  },

  plugins: [
    // Loads benchmarks/results/*.jsonl into global data for the chart
    // components. Reads BENCH_RESULTS_DIR when set (fixtures during dev).
    './plugins/benchmark-results',
    // CI-only: on case-insensitive dev filesystems the redirect stub clobbers
    // the real Benchmarks page (see benchmarksRedirect above).
    process.env.CI === 'true' ? benchmarksRedirect : false,
  ],

  themes: [
    '@docusaurus/theme-mermaid',
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        indexDocs: true,
        indexBlog: false,
        // Source lives in the repo's ../docs tree (read in place), not website/docs.
        docsDir: '../docs',
        docsRouteBasePath: '/docs',
        highlightSearchTermsOnTargetPage: true,
        explicitSearchResultPath: true,
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          // Read the existing repo docs/ tree in place — keeps docs/DESIGN.md,
          // docs/METRICS.md, etc. at the paths CLAUDE.md and the README rely on.
          path: '../docs',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.ts',
          editUrl: `${githubUrl}/edit/main/docs/`,
          showLastUpdateTime: true,
          // `docs/benchmarks/` is an autogenerated sidebar *root*, so Docusaurus
          // never turns it into a category and never hoists its index page —
          // that only happens for subdirectories. sidebars.ts declares the
          // category and links it to `benchmarks/index`, so drop that page from
          // the generated children or it renders twice.
          async sidebarItemsGenerator({defaultSidebarItemsGenerator, ...args}) {
            const items = await defaultSidebarItemsGenerator(args);
            if (args.item.dirName !== 'benchmarks') {
              return items;
            }
            return items.filter(
              (item) => !(item.type === 'doc' && item.id === 'benchmarks/index'),
            );
          },
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/favicon.svg',
    colorMode: {
      defaultMode: 'dark',
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'etl-rs',
      logo: {
        alt: 'etl-rs logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          to: '/docs/user-guide/',
          label: 'Docs',
          position: 'left',
        },
        {
          to: '/docs/DESIGN',
          label: 'Design',
          position: 'left',
        },
        {
          to: '/docs/benchmarks',
          label: 'Benchmarks',
          position: 'left',
        },
        {
          // Static rustdoc output published under <baseUrl>/api/ by CI.
          // `pathname://` prefixes baseUrl and bypasses the SPA router.
          to: 'pathname:///api/',
          label: 'API (rustdoc)',
          position: 'left',
        },
        {
          href: githubUrl,
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            { label: 'User Guide', to: '/docs/user-guide/' },
            { label: 'Architecture (Design)', to: '/docs/DESIGN' },
            { label: 'Metrics', to: '/docs/METRICS' },
            { label: 'Benchmarks', to: '/docs/benchmarks' },
          ],
        },
        {
          title: 'Reference',
          items: [
            { label: 'API (rustdoc)', to: 'pathname:///api/' },
            { label: 'docs.rs', href: 'https://docs.rs/etl' },
            { label: 'crates.io', href: 'https://crates.io/crates/etl' },
          ],
        },
        {
          title: 'More',
          items: [
            { label: 'GitHub', href: githubUrl },
            { label: 'Issues', href: `${githubUrl}/issues` },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Marcus Kainth. etl-rs is dual-licensed MIT OR Apache-2.0.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['rust', 'toml', 'bash', 'yaml', 'docker', 'json'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
