import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Hybrid sidebar: humans curate the top-level structure, while the numbered
 * `docs/user-guide/` tree is autogenerated so new pages appear automatically
 * and the existing `NN-` prefixes drive both ordering and pretty labels (via
 * each folder's `_category_.json`).
 *
 * The two canonical long-form documents (`docs/DESIGN.md`, `METRICS.md`) are
 * grouped separately so they don't collide with the user guide's own
 * `07-reference/` section.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide',
    },
    {
      type: 'category',
      label: 'Design & Internals',
      collapsed: false,
      items: ['DESIGN', 'METRICS'],
    },
  ],
};

export default sidebars;
