import fs from 'node:fs';
import path from 'node:path';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Hybrid sidebar: humans curate the top-level structure, while the numbered
 * `docs/user-guide/` tree is autogenerated so new pages appear automatically
 * and the existing `NN-` prefixes drive both ordering and pretty labels (via
 * each folder's `_category_.json`).
 *
 * The canonical long-form documents (`docs/INVARIANTS.md`, `METRICS.md`) are
 * grouped separately so they don't collide with the user guide's own
 * `07-reference/` section.
 */

/**
 * The decision records, in number order, derived from the directory.
 *
 * Not `type: 'autogenerated'`, and the reason is specific. Autogeneration over
 * `dirName: 'adr'` treats `README.mdx` as an ordinary page rather than as the
 * folder's index — Docusaurus only applies that convention to folders *nested
 * inside* the generated tree, and here `adr/` is the tree. The result is the
 * index appearing twice, once as the category link and once as a leaf, and
 * sorted last because it carries no number prefix.
 *
 * Reading the directory keeps the property autogeneration was wanted for: a new
 * record appears without anyone editing this file. `make check-adr` separately
 * holds the records to their index.
 *
 * The `NNNN-` prefix is stripped from the id because Docusaurus's default
 * number-prefix parser strips it from the route — `0001-foo.md` is served at
 * `adr/foo`. A stale id here fails the build rather than degrading quietly.
 */
const adrDir = path.resolve(__dirname, '../docs/adr');
const adrRecords: string[] = fs
  .readdirSync(adrDir)
  .filter((name) => /^\d{4}-[a-z0-9][a-z0-9-]*\.md$/.test(name))
  .sort()
  .map((name) => `adr/${name.replace(/^\d{4}-/, '').replace(/\.md$/, '')}`);

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide',
    },
    {
      type: 'category',
      label: 'Decisions',
      collapsed: true,
      link: { type: 'doc', id: 'adr/README' },
      items: adrRecords,
    },
    {
      type: 'category',
      label: 'Design & Internals',
      collapsed: false,
      items: ['INVARIANTS', 'METRICS'],
    },
  ],
};

export default sidebars;
