import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Hybrid sidebar: humans curate the top-level structure, while the numbered
 * `docs/user-guide/` tree is autogenerated so new pages appear automatically
 * and the existing `NN-` prefixes drive both ordering and pretty labels (via
 * each folder's `_category_.json`).
 *
 * The two canonical long-form documents (`docs/DESIGN.md`, `METRICS.md`) are
 * grouped separately so they don't collide with the user guide's own
 * `07-reference/` section.
 *
 * `docs/benchmarks/` gets an explicit category because an autogenerated
 * `dirName` is a sidebar *root*: Docusaurus only builds a category (and only
 * hoists an index page into it) for subdirectories, so a bare `autogenerated`
 * entry there spills every benchmark page onto the top level and ignores the
 * folder's `_category_.json`. Its children stay autogenerated — ordered by each
 * page's `sidebar_position` — so a new benchmark page appears without touching
 * this file. `docusaurus.config.ts` filters `benchmarks/index` out of those
 * children, since it is already the category's link.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide',
    },
    {
      type: 'category',
      label: 'Design & Internals',
      collapsed: false,
      items: ['DESIGN', 'METRICS'],
    },
    {
      type: 'category',
      label: 'Benchmarks',
      collapsed: false,
      link: { type: 'doc', id: 'benchmarks/index' },
      items: [{ type: 'autogenerated', dirName: 'benchmarks' }],
    },
  ],
};

export default sidebars;
